### ISSUE TITLE
 'function' object has no attribute 'ConfigurationSettings' "

### ISSUE THREAD

**Issue by scoggins** [remg427/misp42splunk#102]
Looks like one of the cleanups in 3.0.6 has introduced an error:

Running the query:

| mispgetioc misp_instance=default_misp eventid=7859

returns data but also:

External search command 'mispgetioc' returned error code 1. Script output = "error_message=AttributeError at "/opt/splunk/etc/apps/misp42splunk/bin/splunklib/searchcommands/reporting_command.py", line 88 : 'function' object has no attribute 'ConfigurationSettings' "

If I edit mispgetioc.py and add:

```
   def map(self, records):
        # self.logger.debug('mispgetioc.map')
        return records
```

back between @Configuration() and def reduce(..) the error goes away.

I'm running splunk 7.2.1 and misp42splunk 3.0.6 (from splunkbase)

**Comment by remg427** [comment]
Thanks for reporting. applied your fix
