### ISSUE TITLE
Create MISP Events

### ISSUE THREAD

**Issue by idev** [remg427/misp42splunk#105]
Hello,

i am wondering if it is useful also to create events from Splunk and add to MISP.
I think if you have already a working connection, it could also be used to POST Events to the MISP?

Kind regards

**Comment by idev** [comment]
Seems there is already a option: misp_alert_create_event.py ? 
But I dont find in the documentation how to use it.

**Comment by remg427** [comment]
Yes this is the option to create MISP  event from results of Splunk Search

Documentation is too short I ll try to elaborate

But principle is you search in Splunk
You build a table of fields starting by misp_  for example misp_domain or misp_ip_dst
you save as alert
You select alert action misp create event in the gui
You fill in the  form
And voilà



Le 8 août 2019 12:10:30 GMT+02:00, idev <notifications@github.com> a écrit :
>Seems there is already a option: misp_alert_create_event.py ? 
>But I dont find in the documentation how to use it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/105#issuecomment-519457141

-- 
Sent with K-9 Mail.
