### ISSUE TITLE
Trying to contact creator of MISP42

### ISSUE THREAD

**Issue by open-source-rs** [remg427/misp42splunk#107]
So, not really a technical issue.

I use this all the time now.
Would like to contact the creator.
Can't seem to find a good contact.
You can find me on twitter.

https://twitter.com/TheosrsOrg

Please PM me there. 
Would like to contribute if possible...

**Comment by remg427** [comment]
See code for contacts

**Comment by open-source-rs** [comment]
10 4
will do - thanks!
