### ISSUE TITLE
CA-Path problem with 3.0.8

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [remg427/misp42splunk#111]
Hi,

with the new version there is a new bug. When I unselect "MISP CA path" then I get an error message during a search "External search command 'mispsearch' returned error code 1. Script output = "error_message=KeyError at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 74 : 'misp_ca_full_path' "" 

I currently don't use certificate check.

Best regards.

**Comment by remg427** [comment]
Ok Will fixe that's asap

Le 19 septembre 2019 08:14:40 GMT+02:00, ITSEC-DACHSER <notifications@github.com> a écrit :
>Hi,
>
>with the new version there is a new bug. When I unselect "MISP CA path"
>then I get an error message during a search "External search command
>'mispsearch' returned error code 1. Script output =
>"error_message=KeyError at
>"/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 74 :
>'misp_ca_full_path' "" 
>
>I currently don't use certificate check.
>
>Best regards.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/111

-- 
Sent with K-9 Mail.
