### ISSUE TITLE
Import MISP data to Threat intel in ES

### ISSUE THREAD

**Issue by mrtompa** [remg427/misp42splunk#113]
Could you please provide more instructions on how to "feed intel to Enterprise Security App."
I´m not sure how to get ES to pick up the CSV files created by the app. I´ve set the included searches to run on a schedule to pull data from MISP.

And how will threat intel be updated or removed in ES when it changes in MISP?

**Comment by xg5-simon** [comment]
If you have Splunk ES then this is probably a question for Splunk Support as you'd need to use the Splunk ES Threat Intel REST API to perform CRUD actions.

**Comment by mrtompa** [comment]
Ok, will look into the API. I got the import working so now will will only need to purge old data.

**Comment by idev** [comment]
I would also suggest to have a look at Enterprise Security Docs:
https://docs.splunk.com/Documentation/ES/6.0.0/Admin/Addthreatintelfromevents

Maybe this helps

**Comment by remg427** [comment]
Thank you
This what is documented for ip domain intell
Havingg a search that generates a CSV file with correct columns ip weight description
- a local lookup to onboard new version
Cheers
-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
I have a full working environment,
first a search |mispgetevent ... | table ip, domain, description, weight | outputlookup my_ip_intel.csv

then a lookup definition
then on ES 5.30 Configure > Data Enrichment > Intelligence Downloads
there create a local lookup pointing to the lookup above 
and voilà
