### ISSUE TITLE
Feature request threat_level

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [remg427/misp42splunk#119]
Hi I forget something.
Can you also add threat_level_id to mispsearch as output?
Thanks.

**Comment by remg427** [comment]
Hello, the problem is that I use this endpoint /attributes/restSearch and in the results, threat_level_id is not set so I cannot propagate as a field

**Comment by ITSEC-DACHSER** [comment]
Yes it is part of the event. That's a pity. Nethertheless, thank you.

**Comment by remg427** [comment]
I am working on a custom command leveraging events/restSearch may be this will help you


Le 31 octobre 2019 10:21:53 GMT+01:00, ITSEC-DACHSER <notifications@github.com> a écrit :
>Closed #119.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/119#event-2759004260

-- 
Sent with K-9 Mail.
