### ISSUE TITLE
Error with mispgetevent.py

### ISSUE THREAD

**Issue by JamesSOC080** [remg427/misp42splunk#122]
When trying to search for an event with the | mispgetevent function, the following error is received:

External search command 'mispgetevent' returned error code 1. Script output = "error_message=AttributeError at "D:\Splunk\etc\apps\misp42splunk\bin\mispgetevent.py", line 293 : 'mispgetevent' object has no attribute 'threat_level' "

This is on version 3.1.0.

**Comment by remg427** [comment]
Sorry my bad
If you can just comment lines 293 and 294
I'll fix asap


Le 4 novembre 2019 18:13:02 GMT+01:00, JamesSOC080 <notifications@github.com> a écrit :
>When trying to search for an event with the | mispgetevent function,
>the following error is received:
>
>External search command 'mispgetevent' returned error code 1. Script
>output = "error_message=AttributeError at
>"D:\Splunk\etc\apps\misp42splunk\bin\mispgetevent.py", line 293 :
>'mispgetevent' object has no attribute 'threat_level' "
>
>This is on version 3.1.0.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/122

-- 
Sent with K-9 Mail.
