### ISSUE TITLE
Error in 'script': Getinfo probe failed for external search command 'mispsearch'

### ISSUE THREAD

**Issue by RANGERBEE** [remg427/misp42splunk#123]
Hello @remg427 ,

Could you tell me what this error is about and how to fix?  I just installed the latest tarball from your repo.       version app: 3.1.0        MISP 2.4.117 

**Error in 'script': Getinfo probe failed for external search command 'mispsearch'**

Thank you!

**Comment by RANGERBEE** [comment]
This is my search:

| mispsearch misp_instance=default_misp field=id.resp_h onlyids="N" gettag="Y"

**Comment by remg427** [comment]
Hi, I have to update documentation but I removed the param gettag and mispsearch returns by default **attributes** tags if any (as it has not extra cost)
'''
 | mispsearch misp_instance=ops field=md5 onlyids=f
''' 
works without errors.
I have just noticed that param onlyids is uneffective for this kind of search. I will certainly remove it in future
there other params to collect info at event level but not implemented yet

**Comment by RANGERBEE** [comment]
I just upgraded from 3.0.9 to 3.1.1 of app.
I just upgraded MISP to 2.4.117.

After setup of the input I still cannot seem to connect to MISP.

Is there a setting on the MISP user I am missing?
Is there anything on the searchhead I need to update with this new version 3.1.1 build of app?

Here is search and it produces no results...
| mispsearch misp_getioc=default_misp eventid=1267

This is what I use to prove the api connection works. It has always worked as a simple query to hit MISP.

Any ideas?

**Comment by RANGERBEE** [comment]
Log output from Splunk:
```yaml
11-05-2019 15:10:51.566 INFO  script - found script file=/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py
11-05-2019 15:10:51.566 INFO  script - stderr for script mispsearch will be added to search.log
11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__ misp_getioc=default_misp eventid=1247':  Traceback (most recent call last):
11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__ misp_getioc=default_misp eventid=1247':    File "/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py", line 237, in <module>
11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__ misp_getioc=default_misp eventid=1247':      loglevel = logging_level()
11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__ misp_getioc=default_misp eventid=1247':    File "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 27, in logging_level
11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__ misp_getioc=default_misp eventid=1247':      if loglevel is not None:
11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__ misp_getioc=default_misp eventid=1247':  UnboundLocalError: local variable 'loglevel' referenced before assignment
11-05-2019 15:10:51.814 ERROR script - Getinfo probe failed for external search command 'mispsearch'
```

**Comment by remg427** [comment]
Ok now I see. Set debugging level to something different from default and then backbti what you want
I'll fix that ASAP to initiate with a default value


Le 5 novembre 2019 16:49:02 GMT+01:00, RANGERBEE <notifications@github.com> a écrit :
>Log output from Splunk:
>```yaml
>11-05-2019 15:10:51.566 INFO  script - found script
>file=/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py
>11-05-2019 15:10:51.566 INFO  script - stderr for script mispsearch
>will be added to search.log
>11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from
>'/opt/splunk/bin/python
>/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__
>misp_getioc=default_misp eventid=1247':  Traceback (most recent call
>last):
>11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from
>'/opt/splunk/bin/python
>/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__
>misp_getioc=default_misp eventid=1247':    File
>"/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py", line 237, in
><module>
>11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from
>'/opt/splunk/bin/python
>/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__
>misp_getioc=default_misp eventid=1247':      loglevel = logging_level()
>11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from
>'/opt/splunk/bin/python
>/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__
>misp_getioc=default_misp eventid=1247':    File
>"/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 27, in
>logging_level
>11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from
>'/opt/splunk/bin/python
>/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__
>misp_getioc=default_misp eventid=1247':      if loglevel is not None:
>11-05-2019 15:10:51.798 ERROR ScriptRunner - stderr from
>'/opt/splunk/bin/python
>/opt/splunk/etc/apps/misp42splunk/bin/mispsearch.py __GETINFO__
>misp_getioc=default_misp eventid=1247':  UnboundLocalError: local
>variable 'loglevel' referenced before assignment
>11-05-2019 15:10:51.814 ERROR script - Getinfo probe failed for
>external search command 'mispsearch'
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/123#issuecomment-549866429

-- 
Sent with K-9 Mail.

**Comment by RANGERBEE** [comment]
confirmed. All good now!!     Thanks!
