### ISSUE TITLE
support for SHC?

### ISSUE THREAD

**Issue by MattUebel** [remg427/misp42splunk#125]
👋 has this been tested with search head clusters?

**Comment by remg427** [comment]
Version 3.0.9 yes
3.1.x not yet

Le 5 novembre 2019 16:10:25 GMT+01:00, Matt Uebel <notifications@github.com> a écrit :
>👋 has this been tested with search head clusters?>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/remg427/misp42splunk/issues/125

-- 
Sent with K-9 Mail.
