### ISSUE TITLE
misp_ip_intel lookup omits MISP events that have only a domain attribute

### ISSUE THREAD

**Issue by erik6924** [remg427/misp42splunk#127]
`mvexpand` removes events if the field is blank - see [Splunk Answers - "
Why does "mvexpand X" remove events with X=NULL?"](https://answers.splunk.com/answers/330237/why-does-mvexpand-x-remove-events-with-xnull.html)

This means that the domain column in `misp_ip_intel.csv` is always empty.

A modification like the following preserves MISP events with only a domain value.

```
| eval description = "MISP e" + misp_event_id | rename misp_domain AS domain
| eval ip = mvappend(misp_ip_dst,misp_ip_src) 
| eval ip = coalesce(ip,"preserve_single_value_ip")
| mvexpand ip
| eval ip = if(ip="preserve_single_value_ip", null(), ip)
```

**Comment by remg427** [comment]
Thank you. I have updated the saved search with your fix in version 3.1.3
