### ISSUE TITLE
Disable httpS requirement

### ISSUE THREAD

**Issue by ec4n6** [remg427/misp42splunk#132]
Hi, for testing, is there a way to disable the https requirement when setting up the input?

**Comment by remg427** [comment]
Hi,
Thanks forvtesting
You have to edit line 366 of https://github.com/remg427/misp42splunk/blob/master/misp42splunk/appserver/static/js/build/globalConfig.json to changevthe regex to
https?://
The rest should be OK


Le 8 janvier 2020 18:10:29 GMT+01:00, Erick Cheng <notifications@github.com> a écrit :
>Hi, for testing, is there a way to disable the https requirement when
>setting up the input?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/132

-- 
Sent with K-9 Mail.

**Comment by ec4n6** [comment]
@remg427 Thanks for the help. I was able to circumvent the https requirement by updating it to `http` in `apps/misp42splunk/local/inputs.conf` file. After updating, the command runs but returns 0 results. The same command with https returns results.

I'm not sure where its breaking, but consider this a feature request to support http :)

Thanks again for this app and help!
