### ISSUE TITLE
Dashboard Example Data

### ISSUE THREAD

**Issue by idev** [remg427/misp42splunk#133]
Hello,

so I am able to connect to my MISP, but I am struggeling to utilize the Demo Dashboard.
I understand the Index an Interval provided in the configuration is currently not used.

But it would be helpful to show the search which is needed to fill the index (with the requiered fields).
Is it possible to add the search for example to the readme.md of the Dashboard Example?

Kind regards!

**Comment by idev** [comment]
Something like:

| mispgetioc misp_instance=default_misp pipesplit=true  add_description=true category="External analysis,Financial fraud,Internal reference,Network activity,Other,Payload delivery,Payload installation,Payload type,Persistence mechanism,Person,Social network,Support Tool,Targeting data" last=1h to_ids=true geteventtag=true warning_list=true not_tags="osint:source-type=\"block-or-filter-list\""
| eval ip=coalesce(misp_ip_dst, misp_ip_src,misp_ip)
| eval domain=misp_domain
| eval src_user=coalesce(misp_email_src, misp_email_src_display_name)
| eval subject=misp_email_subject
| eval file_name=misp_filename
| eval type = misp_type
| eval file_hash=coalesce(misp_sha1, misp_sha256, misp_sha512, misp_md5, misp_ssdeep)
| eval url=coalesce(misp_url,misp_hostname)
| eval http_user_agent=misp_user_agent
| eval registry_value_name=misp_regkey
| eval registry_value_text=if(isnotnull(misp_regkey),misp_value,null)
| eval weight=case(match(misp_tag,"tlp:white"),20,match(misp_tag,"tlp:green"),40,match(misp_tag,"tlp:amber"),80,match(misp_tag,"tlp:red"),100,true(),50)
| eval description = misp_description
| eval event_id = misp_event_id
| eval uuid = misp_uuid
| table event_id,domain,description,file_hash,file_name,http_user_agent,ip,registry_value_name,registry_value_text,src_user,subject,url,type,weight,uuid | collect index=misp

**Comment by idev** [comment]
I also don't know how to use limit / page if your MISP hold events with huge attribute lists. For performance considerations there should be somekind of limit / pagenation usage?!

**Comment by remg427** [comment]
Hi
Limit is set to 1000 by default
You can change that with limit=XXX if you set to 0 then there is no limit
If you set limit=1000 and you get 1000 results then there is more and you can relaunch the search with limit=1000 and page=2
If you have 1000 results then you launch with page 3 and so on
This is not optimum that's why I have nightly scheduled search that append last day attributes to several lookups and I use those lookups in dashboard
Or you save to index and then reused from index
-- 
Sent with K-9 Mail.

**Comment by idev** [comment]
Thank you for your feedback.

My question is, how to properly fill a index with a sheduled search and the knowledge to handle events with attributes > 30.000.

Maybe this "index saving" have to be done by a python or scripted input script.
Perhaps the project "The-Hive" can be some inspiration, there is also a script filling up there own database with the misp events:
https://github.com/TheHive-Project/TheHive/tree/master/thehive-misp/app/connectors/misp
(I suspekt it is the MispExport.scala)

Kind regards

PS: great work - i love the project!

**Comment by ykorkmaz** [comment]
Hi all,

Just a quick question. Is there a specific reason not to include the "Antivirus detection" and "Artifacts dropped" attribute categories to the search query?

Best regards

**Comment by remg427** [comment]
Hi
No specific reasons you can add and adapt as you like
-- 
Sent with K-9 Mail.
