### ISSUE TITLE
mispsight command error

### ISSUE THREAD

**Issue by ykorkmaz** [remg427/misp42splunk#134]
Hi,

I tried to run the mispsight command and got the following error on Splunk. Does anyone happen to know the reason? 

External search command 'mispsight' returned error code 1. Script output = "error_message=NameError at "/opt/splunk/etc/apps/misp42splunk/bin/mispsight.py", line 118 : global name 'body' is not defined ".

**Comment by remg427** [comment]
Hi,
this is a bug. set logging level to something different than DEBUG as a temporary work around

**Comment by ykorkmaz** [comment]
Thanks for the response, I commented out the line 118 in mispsight.py and problem resolved.

Not sure where to set the log level, setting log level in misp42splunk_settings.conf did not work.

**Comment by remg427** [comment]
Ok that's work too
On the GUI, there is inputs menu and onevof the tabs sets logging level

Le 20 janvier 2020 11:12:22 GMT+01:00, "Ya.Ko" <notifications@github.com> a écrit :
>Thanks for the response, I commented out the line 118 in mispsight.py
>and problem resolved.
>
>Not sure where to set the log level, setting log level in
>misp42splunk_settings.conf did not work.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/134#issuecomment-576202772

-- 
Sent with K-9 Mail.
