### ISSUE TITLE
Splitting malware_sample attributes with pipesplit = t

### ISSUE THREAD

**Issue by ykorkmaz** [remg427/misp42splunk#141]
Hi,

It would be nice if malware_sample type attributes are split into two fields, filename and hash, when pipesplit is set to true.

Regards,
ya.ko

**Comment by remg427** [comment]
It should be the case 
Ok another issue
I have a working code for multivalue object thanks to your sample. I need to fix attributes tags and i am going to propose an unfiltered json output

-- 
Sent with K-9 Mail.

**Comment by ykorkmaz** [comment]
Sure, please find attached the sample event with two attributes of type malware-sample:
[misp-sample-malware-event.zip](https://github.com/remg427/misp42splunk/files/4539152/misp-sample-malware-event.zip)

**Comment by ykorkmaz** [comment]
Did you take a look at the sample event, is it also the case for you?

**Comment by remg427** [comment]
Hello,
for this one I have done nothing.
I have the feeling it is the only case where value contains a | and name not.
so in splunk you can test for type and if malware_sample split the value using | as delimiter

**Comment by ykorkmaz** [comment]
That's correct, it is about those type of attributes. 

Yes, I have already implemented that in Splunk.
