### ISSUE TITLE
MISP Warning Lists are ignored (Version 3.1.5)

### ISSUE THREAD

**Issue by Daniel-CS-Team** [remg427/misp42splunk#147]
We use mispgetioc to pull MISP Events and then do Retorhunts in our Splunk. This week, we had the issue that one of the IOCs was the domain 1drv.ms (Link shortener for Microsoft OneDrive). in MISP, this is clearly marked by two warning lists. But when importing to Splunk, this IOC is imported, wheter I user warning_list=true or false or ommit it completely. I also use to_ids=true and I saw in your code, that this sets warning_list to true anyways. But this does not have any effect. Even in the results, there is no field for Warning list. 

Expected Behavior: if warning_list=true, all IOCs on a warning list are filtered out and not imported
Actual Behavior: the flag warning_list has no effect at all

**Comment by remg427** [comment]
Hi,
if you put logging level to DEBUG you will find in logs var/log/splunk/misp42.log the exact request body
you can copy it and use directly on MISP REST client to confirm the issue is on mispgetioc or not

**Comment by Daniel-CS-Team** [comment]
Sorry, for my late response. I will check with our Splunk team for the debug log. 

In the meantime, I tested the REST API with CURL and it works as expected, meaning if you set "enforceWarninglist": "true" in the POST Body, it filters attributes on the warning list. If this parameter is not set, the very same attribute is returned (as expected).
However, if I serach for the same Event ID and attribute (and of course MISP instacance) using  mispgetioc the attribute is returned regardless of the warning_list flag set to true, false or omitted entirely. 
For me, this strongly indicates an issue in misp42splunk and not with the MISP API itself. 
Unfortuamtely, the usage of warning-lists is very necessary to get this integration to production, because otherwise the False Positive Rate is way to high.

**Comment by remg427** [comment]
Hello,
I acknowledged the issue and this is fixed in latest release. Wrong key was used in json request.
Best
-- 
Sent with K-9 Mail.

**Comment by Daniel-CS-Team** [comment]
Hi,

thank you very much. We will install the update ASAP.

Warm regards
