### ISSUE TITLE
Feature Request: Import IOCs as Events, not Table (Version 3.1.5)

### ISSUE THREAD

**Issue by Daniel-CS-Team** [remg427/misp42splunk#148]
When using mispgetioc, the results are always returned in a table. This is not very usable to further process the IOCs in Splunk. It would be more natural to Splunk if the IOCs would be returned as Events. The user could the easily use the table command, if a table view is required.

**Comment by remg427** [comment]
Hi,
mispgetioc and mispgetevent are reportingcommand so there is no event in the definition of Splunk.
the tabular output is convenient to store in a lookup or event an index.
with latest version you can use param output=raw
in this mode it is still a tabular view but just parsing the first level of the JSON objects returned by MISP API so you can process and extract the info you need
