### ISSUE TITLE
Error when using pipesplit and regkey|value (Version 3.2.1)

### ISSUE THREAD

**Issue by Daniel-CS-Team** [remg427/misp42splunk#156]
Hi remg427,

thank you for your great work here. 
I am sorry, but i found another bug in the current version (3.2.1):
This works fine: "| mispgetioc misp_instance=misp_intern to_ids=true warning_list=true pipesplit=**false** type="regkey|value,regkey" eventid=64189", Tested with misp_value of "HKU\upm_S-1-5-***********_network\Software\Policies\Microsoft\office\16.0\common\security\filevalidation\disablereporting|1"
But this fails: "| mispgetioc misp_instance=misp_intern to_ids=true warning_list=true pipesplit=**true** type="regkey|value,regkey" eventid=64189" with the follwoing error: "External search command 'mispgetioc' returned error code 1. Script output = "error_message=TypeError at "/opt/splunk/etc/apps/misp42splunk/bin/mispgetioc.py", line 573 : coercing to Unicode: need string or buffer, list found ". "

I assume, there is some issue with the "\" in the regkey? Because other misp_types with a pipe work just fine, so far, I only encoutered this error with regkey|value.

Kind regards

**Comment by remg427** [comment]
sorry for that,
work around is to do the job on splunk SPL
will be fixed in 3.2.2

**Comment by remg427** [comment]
resolve in >= 3.2.2

**Comment by remg427** [comment]
resolve in >= 3.2.2
