### ISSUE TITLE
Unable to start a new connection

### ISSUE THREAD

**Issue by spartan117au** [remg427/misp42splunk#157]
I'm unable to pull anything from MISP into our index (misp), with the following error in Splunk;

2020-06-22 11:40:09,816 INFO pid=123230 tid=MainThread file=connectionpool.py:_new_conn:758 | Starting new HTTPS connection (1): 127.0.0.1

We are however able to pull IOCs through other means like Powershell.

**Comment by remg427** [comment]
Hi,
Thanks for using
There is no automatic collection based on inputs. I used addon builder to make the app so input menu was handy to configure the app but turns to be misleading
To get data into splunk use custom commands mispgetioc or mispgetevent instead and save into a lookup or an index as you prefer.
Remi
-- 
Sent with K-9 Mail.

**Comment by spartan117au** [comment]
> Hi, Thanks for using There is no automatic collection based on inputs. I used addon builder to make the app so input menu was handy to configure the app but turns to be misleading To get data into splunk use custom commands mispgetioc or mispgetevent instead and save into a lookup or an index as you prefer. Remi -- Sent with K-9 Mail.

Ah thanks mate!
