### ISSUE TITLE
Feature request - Add tag to Sighting Alert

### ISSUE THREAD

**Issue by cohenshimi** [remg427/misp42splunk#158]
hey,

Is it possible to add TAG that Sent to MISP from Sighting Alert ? 
We need the option to know where the attribute watched in the network without looking for this in Splunk. 
for example send "index" field as TAG .

Thanks!

**Comment by remg427** [comment]
Hello,
endpoint sightings/add support following params
{
    "values": "mandatory",
    "id": "mandatory",
    "type": "optional",
    "source": "optional",
    "timestamp": "optional",
    "date": "optional",
    "time": "optional"
}
so I guess what you would like is to pass source to the alert. correct? if yes i can do that for 3.2.2

**Comment by cohenshimi** [comment]
Yes it would be great.

Thanks 👌

**Comment by remg427** [comment]
implemented in 3.2.2

**Comment by remg427** [comment]
resolve in >= 3.2.2

**Comment by cohenshimi** [comment]
Hey,
first of all thank you very much,
How can I apply this, do you have an example?
I saw that you added a link to the link with an explanation but the link is broken.

Thank you,
Shimi Cohen
