### ISSUE TITLE
last json parameter returns nothing

### ISSUE THREAD

**Issue by aungthurhahein** [remg427/misp42splunk#163]
Hi,

I was trying to make some simple lookup queries and found out "last" parameter is not working. How can I troubleshoot that?
Any help is appreciated.

```
# By EventID (Work)
| mispgetioc misp_instance=default_misp pipesplit=true add_description=true eventid=81

# By Date From (Work)
| mispgetioc misp_instance=default_misp pipesplit=true add_description=true date="2020-07-01"

# By Duration (Didn't return any data)
| mispgetioc misp_instance=default_misp pipesplit=true add_description=true last=30d

```

**Comment by remg427** [comment]
Hi, thank you using misp42splunk
Have you any event published on your MISP for the last 30d? last is an alias for published_timestamp.
on a general approach, a query that works with the REST Client on MISP GUI should work with misp42splunk either by breaking by paramaters or by passing the JSON request from the REST client to json_request.
You can also set logging level to debug and search in misp42.log for string mispgetioc request body:
you should see in logs the JSON request sent to MISP API. You can take that payload and test it on MISP REST client
hope it helps
also to be sure upgrade to 3.2.2

**Comment by aungthurhahein** [comment]
Thanks. I didn't realize the condition of events needs to publish.
