### ISSUE TITLE
last parameter excluding current day

### ISSUE THREAD

**Issue by nordef** [remg427/misp42splunk#164]
When fetching data from last 50 days (or 30, or 1 - does not seem to matter), we are missing events from current day. Any ideas of how we can troubleshoot this, or if this is a known issue? 

`| mispgetioc misp_instance=xyz pipesplit=true add_description=true category="External analysis" last=50d to_ids=true geteventtag=true warning_list=true not_tags="osint:source-type=\"block-or-filter-list\""`

FYI: Splunk 8.0.3 and MISP42 v. 3.2.1

**Comment by remg427** [comment]
Hi,
thank you for using misp42splunk
this is not known for me. I regularly use last=1d, last=12H, etc. and get attributes from events published within the day.

**Comment by nordef** [comment]
Hi, 

Thanks for the quick reply! 
When I'm using date I get all events from current day. But when I'm using last=1d or last=12H or similar I'm not getting all events. E.g. last=4H gives all events from last four hours. last=24H does not give the most recents events that has occured during the last hours.

**Comment by remg427** [comment]
Ah OK
It is because by default limit is set to 1000. Add limit=0 and you will get all events.
If this is too much you can use page in combination of limit to query all events in a sequence of events
Best
-- 
Sent with K-9 Mail.
