### ISSUE TITLE
Upgrade Notes?

### ISSUE THREAD

**Issue by idev** [remg427/misp42splunk#165]
Hello,

are there any breaking changes if i upgrade from 3.1.4 to the latest realease?
As far as I see Splunk 7.x and Splunk 8.x is supported. 

I also read something a new mispcollect command, but can not find any documentation on this and how it is different to mispgetioc (params?)?

Thank you

**Comment by remg427** [comment]
Hi,
It should work fine. I changed the class for custom commands but his  backstage
Thank you for using misp42
-- 
Sent with K-9 Mail.

**Comment by idev** [comment]
Ok, thank you!

I also do not understand the difference between mispgetioc and mispcollect; it looks like both commands return a different field set? mispcollect is missing various fields like "misp_comment" and "misp_description".

**Comment by remg427** [comment]
Hi mispcollect returns attributes or events as is and display them as splunk events with the timeline
Remi
-- 
Sent with K-9 Mail.
