### ISSUE TITLE
Feature Request - Add local tags, publish on alert action

### ISSUE THREAD

**Issue by Belrix** [remg427/misp42splunk#166]
It would be helpful to define whether tags are local or global (we do a lot of automation for sec tools based on tags).  Also, a flag to publish event when sent? 
BTW  - big fan of misp42splunk. Really helping us out.

**Comment by remg427** [comment]
Hi, I don't know how to define tags are local from Splunk.  thought you just have to create them as local.Is there any REST query that set this?

**Comment by remg427** [comment]
in version 4 you can publish on creation
regarding local tag, I think that if you create them on MISP as local (not exportable) then you can set them via alert action and it should be fine

**Comment by remg427** [comment]
implemented on 4.0.0
