### ISSUE TITLE
conf files not replicating in SHC

### ISSUE THREAD

**Issue by amirofmn** [remg427/misp42splunk#167]
We've been attempting to get this app working in a 7.3.x SHC and what we've noticed upon setting up a "misp_instance" is the updates to the inputs.conf and any changes that reside in the misp42splunk_settings.conf do not get replicated to the other SH's.  If your SHC is behind a VIP, it becomes a matter of hit-and-miss as to whether an end-user lands on the correct SH.

In our testing, we added the stanza (below) to a server.conf within the app and were successful in getting the "misp_instance" replicated to the other SH's although we have concerns around replicating the inputs.conf as it holds static values that may not and/or should not be replicated to other SH's.  One example of which is a Splunk Administrator wanting to change their default-hostname on a SH.  With the replication settings below in place, by changing the default-hostname via cli (splunk set default-hostname <desired-hostname>) and then restarting the specific SH, the new default-hostname actually gets applied to all the SH's in the cluster which isn't desirable.  Thus, it would be nice to see the "misp_instance" setup to be saved in another misp-like conf file which can then be replicated without impacting any other settings in Splunk.

```
[shclustering]
conf_replication_include.misp42splunk_settings = true
conf_replication_include.inputs = true
```

Hope this made sense.

**Comment by remg427** [comment]
Hello,
misp42splunk has been succesfully deployed on 2 different SHC clusters 7.3 without any problem. SHC are behind a reverse proxy and I have never noticed this issue. Though this is deployedwith ansible so maybe native cluster deployed is bypassed. I will double check
You can safely copy inputs.conf has host value and sourcetype are not used. Inputs.conf is a simple way to declare as many MISP instance as you like ( I have 3).
Btw thanks for using MISP42.


Le 25 septembre 2020 19:07:17 GMT+02:00, AGS <notifications@github.com> a écrit :
>We've been attempting to get this app working in a 7.3.x SHC and what
>we've noticed upon setting up a "misp_instance" is the updates to the
>inputs.conf and any changes that reside in the
>misp42splunk_settings.conf do not get replicated to the other SH's.  If
>your SHC is behind a VIP, it becomes a matter of hit-and-miss as to
>whether an end-user lands on the correct SH.
>
>In our testing, we added the stanza (below) to a server.conf within the
>app and were successful in getting the "misp_instance" replicated to
>the other SH's although we have concerns around replicating the
>inputs.conf as it holds static values that may not and/or should not be
>replicated to other SH's.  One example of which is a Splunk
>Administrator wanting to change their default-hostname on a SH.  With
>the replication settings below in place, by changing the
>default-hostname via cli (splunk set default-hostname
><desired-hostname>) and then restarting the specific SH, the new
>default-hostname actually gets applied to all the SH's in the cluster
>which isn't desirable.  Thus, it would be nice to see the
>"misp_instance" setup to be saved in another misp-like conf file which
>can then be replicated without impacting any other settings in Splunk.
>
>```
>[shclustering]
>conf_replication_include.misp42splunk_settings = true
>conf_replication_include.inputs = true
>```
>
>Hope this made sense.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/167

-- 
Sent with K-9 Mail.

**Comment by amirofmn** [comment]
Yes, to clarify, we're using Splunk native clustering capabilities where the installation of the app within the SHC is performed by the 'deployer'.  In a clean environment without anything installed, if you run a btool against the server.conf, you'll see the inputs.conf is not replicated by default which would prevent the "misp_instance" setup from replicating natively.  This also applies to any logging changes within the app config.

Since were not comfortable enabling Splunk to replicate the inputs.conf and wanted to find a workaround, we took a set of working configurations from a stand-alone Splunk instance (i.e. inputs.conf, passwords.conf and misp42splunk_settings.conf), dropped them into the local folder of the app on the 'deployer' along with our server.conf (but without the inputs replication setting) and pushed into the SHC.  The good news is the "misp_instance" setup showed up successfully on all the search heads.  The bad news is when we attempted to run some of the commands, an error was generated...

```
External search command 'mispgetevent' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 84 : ('local/inputs.conf does not exist. Please configure an inputs entry for %s', 'default') ".
```

Looks like the configuration is required to be in the local folder but if it's deployed via the 'deployer', it will be placed in the 'default' folder.  The only way to get the configuration to reside in the local folder on the SH is to go through the UI and enter all the necessary values but this would then bring us full circle where it's not replicating.  Ideally it would be nice to have both options where we can setup the "misp_instance" in the UI or via the deployer.

What I'm attempting to suggest is a change the app behavior where the setup does not drop it's config directly into the inputs.conf, rather, a separate misp-like conf file which can be enabled for replication safely as we've seen in other security apps.  Wasn't looking for a solution on how to handle the host name in the inputs.conf but simply trying to draw attention that there may be good reason why Splunk does not replicate the inputs.conf by default and the risk with using that file in a SHC for your app's configs.

Let me know if you need any specifics from our environment setup to help you replicate the issues we're seeing.

Thanks for looking into this.

**Comment by remg427** [comment]
Hi, 
I have a look at this issue and the way the TA Add-on Builder is built rely on inputs.conf I don't know how to easily switch to another type of file. I see 3 options
- take into account also default/inputs.conf
- change for addtitional  fields with up to 3 different instances
- change the design like for another app I made with a lookup to define instances and additional fields to safely store the api key

**Comment by amirofmn** [comment]
Short-term, if we take into account the "default/inputs.conf", then we can make the app work by deploying it into the SHC using Splunk's deployer functionality.  

Long-term, users will want the ability to make changes to the app's settings in the UI without always being dependent on the deployer which would ideally use a different file than the inputs.conf.  To see an example of another apps doing so from splunkbase, both Phantom and RecordedFuture have specific conf files for their settings which are replicated safely within a SHC.  I can't speak to how much work is involved to update the MISP app but maybe there is some existing code from those apps which can be leveraged?

**Comment by remg427** [comment]
Hi Thank you for hints
I will have a look at it.
Another option is like I have done for another app by using a lookup for parameters except pasdwords
-- 
Sent with K-9 Mail.

**Comment by amirofmn** [comment]
Sure.  If the lookup option works and it simplifies any work on your end, let's do it.  I haven't seen the other app but might I suggest including a distsearch.conf where it blacklists the lookup from being distributed to the indexers...this assuming the lookup is a csv file and not a kvstore.  I can't imagine the csv file being large but keeping anything out of the knowledge bundle that doesn't need to be there would be appreciated.

**Comment by remg427** [comment]
Hi,
I am working on a cleaner version with a lookup to manage MISP instances as this looks easier for me than via GUI
I will include a distsearch.conf thanks for the hint

**Comment by remg427** [comment]
HI, version 3.3.0 still use inputs GUI to edit inputs.conf. On changes, this file is copied to misp42splunk_instances.conf'.
misp42splunk_instances.conf' is set to be replicated within the SHC. I follow your comment, thanks
If the file exits, it is copied to local/inputs.conf before any action on inputs.
I hope this will do the trick as developing directly a creen for this file was too complex; I still need to study other examples.
Could you test 3.3.0?

**Comment by amirofmn** [comment]
Will test and report back findings this week.

**Comment by amirofmn** [comment]
We tested 4.0.0 in 7.3.x and are happy to report the replication of the inputs is working great.  We can see both new configuration additions as well as removals being replicated successfully within the "misp42splunk_instances.conf" file.  Thank you!
