### ISSUE TITLE
MISP Object Attributes Not Correlated with UUID  

### ISSUE THREAD

**Issue by malvidin** [remg427/misp42splunk#172]
When mispgetioc returns a type of misp_object, the values cannot be correlated to the UUID for each attribute.

The `output=raw` option returns each attribute separately in a JSON blob that can be parsed with spath, but I expected a reproducible way to correlate the attribute UUID and its value from the default table output.

**Comment by remg427** [comment]
Hi, thanks for using misp42
at the moment UUID of attributes of an object are added to the same field misp_attribute_uuid
I see 2 options to achieve what you would like.
1. change behaviour to make misp_type and misp_value multivalue fields containing original types and values in same order as  misp_attribute_uuid. Then on splunk SPL you may use mvzip to group first value and first uuid, 2nd value and 2 uuid and so on and then make a mvexpand and mvsplit; this requires little change on the code but some work on Splunk
2. introduce a new boolean parameter expand_object (default to FALSE to maintain current behaviour) that will put each attribute of an object per line. Then you can group them again using | stats values(*) as * by misp_event_uuid , misp_object_id
