### ISSUE TITLE
Values in MISP_comment field is empty

### ISSUE THREAD

**Issue by divya906** [remg427/misp42splunk#191]
Hi,
We are using MISP42 3.2.1 version and pulling threat feeds, while fetching the feeds value in the filed MISP_comment is empty rest all fields are having values.

Could you please help me to troubleshoot this issue.

Thanks in advance!

**Comment by remg427** [comment]
hello,
thanks for using misp42. Do you have comments on attributes stored on MISP (i.e. from those feeds)?

**Comment by divya906** [comment]
> hello,
> thanks for using misp42. Do you have comments on attributes stored on MISP (i.e. from those feeds)?

Yes

**Comment by remg427** [comment]
Hello,
Could you set logging level to DEBUG and retrieve from.logs request body
then on the misp instance use REST client and that JSON payload to see if you have comments in returned results
-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Could you upgrade to 4.0.1?
-- 
Sent with K-9 Mail.
