### ISSUE TITLE
Query with 1,000 truncate event

### ISSUE THREAD

**Issue by aldoarreolaAZ** [remg427/misp42splunk#196]
All the searchs running with mispgetioc are truncated to 1000 events, can I remove this limit?

| mispgetioc misp_instance=default_misp pipesplit=true  add_description=true category="External analysis,Financial fraud,Internal reference,Network activity,Other,Payload delivery,Payload installation,Payload type,Persistence mechanism,Person,Social network,Support Tool,Targeting data" last=90d to_ids=true geteventtag=true warning_list=true not_tags="osint:source-type=\"block-or-filter-list\""
| eval ip=coalesce(misp_ip_dst, misp_ip_src,misp_ip)
| eval domain=misp_domain
| eval src_user=coalesce(misp_email_src, misp_email_src_display_name)
| eval subject=misp_email_subject
| eval file_name=misp_filename
| eval file_hash=coalesce(misp_sha1, misp_sha256, misp_sha512, misp_md5, misp_ssdeep)
| eval url=coalesce(misp_url,misp_hostname)
| eval http_user_agent=misp_user_agent
| eval registry_value_name=misp_regkey
| eval registry_value_text=if(isnotnull(misp_regkey),misp_value,null)
| eval description = misp_description
| table domain,description,file_hash,file_name,http_user_agent,ip,registry_value_name,registry_value_text,src_user,subject,url,weight

![mispquery](https://user-images.githubusercontent.com/68917729/119025725-02d33480-b96a-11eb-81c9-d860a2fb823a.png)

**Comment by remg427** [comment]
hello,
yes as mentioned in doc, by default limit is et to 1000
add limit=0 to your search to get all results
