### ISSUE TITLE
no misp_instance with specified name found

### ISSUE THREAD

**Issue by gurjie** [remg427/misp42splunk#201]
Hi, thanks for the useful project. I've got an issue with initially setting up the app, installed on a search head. No MISP instance is detected, not sure if this is a duplicate of another issue, or if I'm missing something obvious in the config. 

The following error is generated when viewing any report, and executing any misp related query baked into the app: 
`External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 79 : ('[MC-PC-E03] no misp_instance with specified name found: %s ', 'default_misp') ".`

NB `default_misp` is not the misp instance name which I provided. Hostname definitely set in misp42splunk_instances.conf

I'm unsure as to which port to use for the misp instance. It's definitely reachable via curl on the search head over 8443. 8443 is the port which the web interface uses, not sure if API calls are made to another port specifically. 

Thanks in advance, sorry if there's an obvious answer.

(running misp42splunk 4.0.2, MISP v2.4.148)

![image](https://user-images.githubusercontent.com/36381385/132336945-0f644271-698f-460e-8e80-8d1d964dff7b.png)
![image](https://user-images.githubusercontent.com/36381385/132337054-28820554-2b22-4bf5-a94a-dabd356acc3f.png)
![image](https://user-images.githubusercontent.com/36381385/132337205-39a320fc-c00a-4456-9fd4-9be2348c8a9f.png)
![image](https://user-images.githubusercontent.com/36381385/132337251-a89fa8d0-6161-4185-bd0c-da5d0f85d2eb.png)

**Comment by remg427** [comment]
Hello 
Yes you need to configure at least one instance and then use it with parameter misp_instance=
And api port is the same as gui
-- 
Sent with K-9 Mail.

**Comment by gurjie** [comment]
Hi, thanks. That makes sense, I was able to set the misp_instance parameter for any searches, and successfully made REST API calls to MISP.

However, the dashboard is still not populated with any data as in the first image above. Any "MISP Custom command" will also not allow me to select a misp instance, shown in the following capture:

![image](https://user-images.githubusercontent.com/36381385/132641214-531da362-2fa0-4389-bb7d-5ec440ad3f01.png)
 
My misp42splunk_instances.conf looks like the following:

```
[personal_instance]
misp_instance = personal_instance
client_use_cert = 0
misp_key = ********
misp_url = https://misp.intra.personal.com:8443
misp_use_proxy = 0
misp_verifycert = 1
```

I understand that the following search is used to retrieve a list of possible MISP instances to use when running MISP custom command: 


Many thanks

**Comment by remg427** [comment]
Weird
Just try
| mispgetioc misp_instance=personal_instance last=100d
-- 
Sent with K-9 Mail.

**Comment by gurjie** [comment]
Hi, just to note that I have every other part of the app working now. The above works fine.
