### ISSUE TITLE
Add Timestamp Field for get IOC

### ISSUE THREAD

**Issue by healthrage** [remg427/misp42splunk#204]
timestamp: Restrict the results by the timestamp (last edit). Any event with a timestamp newer than the given timestamp will be returned. In case you are dealing with /attributes as scope, the attribute's timestamp will be used for the lookup. The input can be a timetamp or a short-hand time description (7d or 24h for example). You can also pass a list with two values to set a time range (for example ["14d", "7d"]).

Current Options are Last ( which only works for published events ) and date which only takes a certain date to look for.

If we can add this field it would greatly increase ease of use!

Thanks

**Comment by remg427** [comment]
hello,
actually you can use a range for parameter date.
in principle, anything that works with MISP REST client should work from misp42
