### ISSUE TITLE
Updating values with "0" during updating sighting by value

### ISSUE THREAD

**Issue by schimpy** [remg427/misp42splunk#207]
Hello team,

I managed to sent sightings from Splunk to MISP (both by attribute uuid and by value). 

But when updating sighting by value, also all attributes with zero ("0") value in it got updated (plus all occurences "domain.net"). I am using following SPL:

```
| makeresults 
| eval misp_domain="domain.net"
| sendalert misp_alert_sighting param.misp_instance=misp_default param.title="TEST" param.mode="byvalue" param.type=1
```

Could you see a possible issue here?

**Comment by schimpy** [comment]
Hello @remg427,

Any updates on this issue? Were you able to replicate it at your env.?

Thank you in advance.

Br, schimpy

**Comment by schimpy** [comment]
Hello team, any updates on this?

**Comment by schimpy** [comment]
Hello @remg427, any updates on this issue?

**Comment by remg427** [comment]
Hello, I finally had a look at this. sorry for too long time.
on "all occurrences of domain.net are updated": this is expected when doing sighting by value.

"all attributes with zero ("0") value in it got updated ":  I excluded 0 / "0" from list of values

**Comment by schimpy** [comment]
Hello @remg427, in which version is the bug fixed? Thanks

**Comment by remg427** [comment]
Hello should be in the latest 4.2.2

Le 31 mars 2023 09:42:24 GMT+02:00, schimpy ***@***.***> a écrit :
>Hello @remg427, in which version is the bug fixed? Thanks
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/207#issuecomment-1491455681
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent with K-9 Mail.
