### ISSUE TITLE
last field Deprecated

### ISSUE THREAD

**Issue by rafiki31130** [remg427/misp42splunk#230]
Hi,
The 'last' field is deprecated in MISP.
The right parameter tu use is timestamp, using the last field, the request take a lot longuer than expected and can generate timeouts on important sources.

Can me manualy managed with this parameter: json_request="{\"timestamp\":\"1d\"}"
But it would be great if directly managed by the command.

Thanks !

**Comment by rafiki31130** [comment]
Hi,

My bad, the documentation indicates well that the `last` field is deprecated but replaced by `publish_timestamp`, **not** `timestamp`.

However interesting fact: the request over `timestamp` (corresponding to latest update time) are well faster than `publish_timestamp` (or `last`) surely because `timestamp` is indexed and the other aren't. Don't know if you want to take into account but it can be usefull.

Source, fields detailed list here: [RESTful searches with XML result export](https://www.circl.lu/doc/misp/automation/#search)

Kind regards,
Christian

**Comment by remg427** [comment]
All keys are still supported:
* timestamp: last change on the event
* publish_timestamp: last timestamp the event was published (it could be unpublished since then - check boolean published)
* last (DEPRECATED) but still returning same results as publish_timestamp
