### ISSUE TITLE
HTTP Post Method 

### ISSUE THREAD

**Issue by zeinababdallah** [remg427/misp42splunk#242]
Hello,

I am getting this error while trying to get IOCs from my misp instance to splunk:
[MC503] DEBUG urlib3 POST request failed error=<urllib3.connection.HTTPSConnection object at 0x7fa2e0af3cd0>: Failed to establish a new connection: [Errno 110] Connection timed out url=https://x.x.x.x/attributes/restSearch

is there any idea on how to relsovle this issue?

Thanks in advance.

**Comment by remg427** [comment]
connectivity issue between the search head and MISP server. test with curl
