### ISSUE TITLE
MISP42

### ISSUE THREAD

**Issue by ruzaj** [remg427/misp42splunk#247]
Dear Rami,

we are having problems with connecting MISP42 and Splunk. 
After putting data in configuration tab (misp istance, misp url, misp api key) we still cannot see MISP istance count, its 0.
Can you please advise.

Thanks

**Comment by ruzaj** [comment]
Dear Remi,

thanks for quick answer.
Splunk user can use every command.
where do we use misp_instance = ?

**Comment by remg427** [comment]
Actually the users need this capability rest_properties_get to have the dropdown populated but it is easy to simply type the name of the misp instance
