### ISSUE TITLE
Create event on MISP with multivalue attribute

### ISSUE THREAD

**Issue by jacoporusso-css** [remg427/misp42splunk#251]
Hello,
 I'm trying to use **sendalert misp_alert_create_event** to create on misp an event containing an attribute with multiple values (e.g.: an email object with multiple attachments, as described in the [object description](https://github.com/MISP/misp-objects/blob/main/objects/email/definition.json)).
 Starting from the following mock (semplified to be readable - data is more complex)
 
| makeresults
| eval misp_time=_time, eo_subject="subject", eo_from="address@example.com", eo_attachment=att_name
| eval att_name="a.exe,b.exe"
| makemv att_name delim=","
 
  I tried the following methods but none seems to work:
 - eo_attachment as Splunk multivalue
 - eo_attachment as json array (using makejson command)
 - separating values using delimiters ","/";"

Is there a supported way to do so?

Thanks

**Comment by remg427** [comment]
Hi
Thank you for using misp42
I had a quick look and the code of modalert_misp_alert_create_event_helper.py line 131 takes field value.
Multivalue is not really supported and I will work on that.

With current version i see 2 options
First makes eo_attachment a valid string list
"[\"filename1\",\"filename2\"]"
Maybe this will be processed correctly by MISP API

second is with misprest

You will need to build the full json_request following the API documentation of /event/add with 2 additional keys Attribute containing a list of attributes and Object with the list of objects

Then you call misprest using map

| map search="| misprest misp_instance= method=POST target=/event/add json_request=$json_request$"

I cannot test it now but will on weekend
Remi

Le 2 novembre 2023 17:21:19 GMT+00:00, jacoporusso-css ***@***.***> a écrit :
>Hello,
> I'm trying to use **sendalert misp_alert_create_event** to create on misp an event containing an attribute with multiple values (e.g.: an email object with multiple attachments, as described in the [object description](https://github.com/MISP/misp-objects/blob/main/objects/email/definition.json)).
> Starting from the following mock (semplified to be readable - data is more complex)
> 
>| makeresults
>| eval misp_time=_time, eo_subject="subject", ***@***.***", eo_attachment=att_name
>| eval att_name="a.exe,b.exe"
>| makemv att_name delim=","
> 
>  I tried the following methods but none seems to work:
> - eo_attachment as Splunk multivalue
> - eo_attachment as json array (using makejson command)
> - separating values using delimiters ","/";"
>
>Is there a supported way to do so?
>
>Thanks
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/251
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent with K-9 Mail.

**Comment by jacoporusso-css** [comment]
Hi Remi,
 thanks for the insight. I just analyzed how multivalue are represented (each value is separated by newline) and found a fix to handle them.
 Changing the for loop at line 283 in modalert_misp_alert_create_event_helper.py it works as expected!
 
         for key, value in list(row.items()):
            attribute_metadata = attribute_baseline.copy()
            for single_value in str(value).split("\n"):
                helper.log_info("key: {}, single_value: {}".format(key,single_value))
                if key.startswith("misp_") and single_value not in [None, '']:
                    misp_key = str(key).replace('misp_', '').replace('_', '-')
                    attribute_metadata['type'] = misp_key
                    attribute_metadata['value'] = str(single_value)
                    attributes.append(attribute_metadata)
                elif key.startswith("fo_") and single_value not in [None, '']:
                    fo_key = str(key).replace('fo_', '').replace('_', '-')
                    object_attribute = store_object_attribute(
                        fo_template['attributes'], fo_key, str(single_value),
                        metadata=attribute_metadata)
                    if object_attribute:
                        fo_attribute.append(object_attribute)
                elif key.startswith("eo_") and single_value not in [None, '']:
                    eo_key = str(key).replace('eo_', '').replace('_', '-')
                    object_attribute = store_object_attribute(
                        eo_template['attributes'], eo_key, str(single_value),
                            metadata=attribute_metadata)
                    if object_attribute:
                        eo_attribute.append(object_attribute)
                elif key.startswith("no_") and single_value not in [None, '']:
                    no_key = str(key).replace('no_', '').replace('_', '-')
                    object_attribute = store_object_attribute(
                        no_template['attributes'], no_key, str(single_value),
                        metadata=attribute_metadata)
                    if object_attribute:
                        no_attribute.append(object_attribute)
                elif key in data_type:
                    misp_key = data_type[key]
                    attribute_metadata['type'] = misp_key
                    attribute_metadata['value'] = str(single_value)
                    attributes.append(attribute_metadata)

**Comment by remg427** [comment]
Thank you very much
I have implemented your fix in 4.3.1
