### ISSUE TITLE
Misp tagging local or global

### ISSUE THREAD

**Issue by sumit2929** [remg427/misp42splunk#254]
Can you help to find, how i can create a local tag in misp from splunk.

currently from the splunk search i am able to make global tag into misp where field name use is misp_tag.

If i want to create local tab , is there something different i have to do and how ?

**Comment by remg427** [comment]
Hi
One way is to look how to do it directly calling   misp api
And then reproduce the call with misprest


Le 21 novembre 2023 12:41:32 GMT+01:00, sumit2929 ***@***.***> a écrit :
>Can you help to find, how i can create a local tag in misp from splunk.
>
>currently from the splunk search i am able to make global tag into misp where field name use is misp_tag.
>
>If i want to create local tab , is there something different i have to do and how ?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/254
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent with K-9 Mail.
