### ISSUE TITLE
UnboundLocalError when there is error in connection

### ISSUE THREAD

**Issue by wintermute101** [remg427/misp42splunk#257]
When you try to connect to MISP instance and there is connection error, instead of showing error message there is error in code that tries to show "r" response of misp_url_request which is not set in this case.

`UnboundLocalError at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 291 : local variable 'r' referenced before assignment`

**Comment by wintermute101** [comment]
I think it was already fixed, I do not see error in git version.

**Comment by remg427** [comment]
Hello
This is fixed in 4.3.2 avalaible on github
Checks ongoing on splunkbase before validation


Le 21 décembre 2023 12:27:52 GMT+01:00, wintermute101 ***@***.***> a écrit :
>When you try to connect to MISP instance and there is connection error, instead of showing error message there is error in code that tries to show "r" response of misp_url_request which is not set in this case.
>
>`UnboundLocalError at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 291 : local variable 'r' referenced before assignment`
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/257
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent with K-9 Mail.
