### ISSUE TITLE
Issue No such file or directory in search "|mispgetioc last=30d type="yyy" misp_instance=XXXX"

### ISSUE THREAD

**Issue by spiazzi** [remg427/misp42splunk#258]
Hi all,

we receive this error if we do this query (masked):

|mispgetioc last=30d type="yyy" misp_instance=XXXX

No such file or directory url=https://misp.xxx.xx/attributes/restSearch body={'last': '30d', 'returnFormat': 'json', 'withAttachments': False, 'includeEventUuid': True, 'deleted': False, 'type': 'yyy', 'page': 1, 'limit': 1000}

What we can check?
Misp instance seems synced and authenticated on the other side.

**Comment by remg427** [comment]
Hi

Which version of misp42 do you use?
On linux or windows box?


Le 25 janvier 2024 17:43:51 GMT+01:00, spiazzi ***@***.***> a écrit :
>Hi all,
>
>we receive this error if we do this query (masked):
>
>|mispgetioc last=30d type="yyy" misp_instance=XXXX
>
>No such file or directory url=https://misp.xxx.xx/attributes/restSearch body={'last': '30d', 'returnFormat': 'json', 'withAttachments': False, 'includeEventUuid': True, 'deleted': False, 'type': 'yyy', 'page': 1, 'limit': 1000}
>
>What we can check?
>Misp instance seems synced and authenticated on the other side.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/258
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent with K-9 Mail.

**Comment by spiazzi** [comment]
Linux

**Comment by spiazzi** [comment]
any idea?

**Comment by remg427** [comment]
Hi, What is the role on MISP of the user for which the API key has been created?
