### ISSUE TITLE
Problem with search_command.py field limit

### ISSUE THREAD

**Issue by upfischer** [remg427/misp42splunk#261]
We get the following error when using the misp42 Splunk App:
"/splunk/etc/apps/misp42splunk/lib/splunklib/searchcommands/search_command.py", line 291 : field larger than field limit (10485760) ".

Are there Limitations for the 'mispsearch' and other commands in this TA and if yes, is it possible to fix this problem?

**Comment by remg427** [comment]
HI, I am not sure from which platform this limitation comes from? do you know if it is from Splunk or from MISP API?

**Comment by remg427** [comment]
Maybe setting limit=1 would be a solution
