### ISSUE TITLE
Problem with search

### ISSUE THREAD

**Issue by julbo250** [remg427/misp42splunk#265]
Hi,
When i get IOC with the command : | mispgetioc misp_instance=MISP_xxxx last="1d" 
I obtain this error on Splunk :  

[MC503] DEBUG urlib3 POST request failed error=[Errno 13] Permission denied url=https://xxxx/attributes/restSearch body={'last': '1d', 'returnFormat': 'json', 'withAttachments': False, 'includeEventUuid': True, 'deleted': False, 'page': 1, 'limit': 1000}  

My MISP instance in on TLS1.3.

 Is it possible to fix this problem ?

**Comment by remg427** [comment]
hello, could you check with curl that the request works outside MISP42?

**Comment by julbo250** [comment]
hi, yes the curl request works fine. I have the same problem of this : https://github.com/remg427/misp42splunk/issues/232 (last post)

**Comment by remg427** [comment]
I think the error comes from the permissions of the MISP account and/or the type of auth keys. It is recommended to switch to advanced auth keys and to give sync permissions
