### ISSUE TITLE
mispsight command error

### ISSUE THREAD

**Issue by VLFrank** [remg427/misp42splunk#269]
Hello,

When I try to fetch the sighting from MISP I get this error, all the other commands works except this one:

SPL :
| makeresults 
| eval domain="test.com"
| mispsight misp_instance=MISP field=domain

Error in 'mispsight' command: External search command exited unexpectedly with non-zero error code 1.

When I check MISP42 logs I dont see anything about this .

Any Idea how I can fix this ?

Thank you

**Comment by remg427** [comment]
Hello
Could you set logging mode to DEBUG and then inspect Splunk job search logs to see the error messages?

**Comment by VLFrank** [comment]
Heres what I have in the search.log :

09-10-2024 08:04:24.998 INFO  ChunkedExternProcessor [219578 searchOrchestrator] - Running process: /opt/splunk/bin/python3.7 /opt/splunk/etc/apps/misp42splunk/bin/mispsight.py
09-10-2024 08:04:25.015 ERROR ChunkedExternProcessor [219586 ChunkedExternProcessorStderrLogger] - stderr:   File "/opt/splunk/etc/apps/misp42splunk/bin/mispsight.py", line 19
09-10-2024 08:04:25.015 ERROR ChunkedExternProcessor [219586 ChunkedExternProcessorStderrLogger] - stderr:     ·
09-10-2024 08:04:25.015 ERROR ChunkedExternProcessor [219586 ChunkedExternProcessorStderrLogger] - stderr:     ^
09-10-2024 08:04:25.015 ERROR ChunkedExternProcessor [219586 ChunkedExternProcessorStderrLogger] - stderr: SyntaxError: invalid character in identifier
09-10-2024 08:04:25.016 ERROR ChunkedExternProcessor [219578 searchOrchestrator] - EOF while attempting to read transport header read_size=0
09-10-2024 08:04:25.016 ERROR ChunkedExternProcessor [219578 searchOrchestrator] - Error in 'mispsight' command: External search command exited unexpectedly with non-zero error code 1.
09-10-2024 08:04:25.017 ERROR SearchPhaseGenerator [219578 searchOrchestrator] - Fallback to two phase failed with SearchProcessorException: Error in 'mispsight' command: External search command exited unexpectedly with non-zero error code 1.
09-10-2024 08:04:25.017 WARN  SearchPhaseGenerator [219578 searchOrchestrator] - Failed to create search phases: exception=31SearchProcessorMessageException, error=Error in 'mispsight' command: External search command exited unexpectedly with non-zero error code 1.
09-10-2024 08:04:25.020 INFO  SearchStatusEnforcer [219578 searchOrchestrator] - sid=1725969864.165453_267DEFC0-5175-4A3B-BDD0-E12BCF5D2FF5, newState=BAD_INPUT_CANCEL, message=Error in 'mispsight' command: External search command exited unexpectedly with non-zero error code 1.

**Comment by VLFrank** [comment]
Found it,

So for some reason there were a random . in the python script .


Thanks for the help Remi !

**Comment by remg427** [comment]
will be fixed in 4.4.x
