### ISSUE TITLE
Date parameter in mispgetioc not returning correct data

### ISSUE THREAD

**Issue by node011** [remg427/misp42splunk#270]
while using mispgetioc to retrieve data on specific time interval (date="2024-10-18,2024-10-20") the search result returned data with inaccurate timestamp ( results with timestamp 2024-01-02 ), i tried all other viable date format as input but always getting results with inaccurate timestamp, while using filter like "last=3d" it return data with correct timestamp, 

ps: attaching you screenshots of issue
![image (1)](https://github.com/user-attachments/assets/8e966672-7c9e-4988-9a22-feb1b75f4590)
while using single date as filter 

![image (2)](https://github.com/user-attachments/assets/8a41ad04-18fa-4fab-a734-9425d9a3b0bb)
while using time range as filter

![image (3)](https://github.com/user-attachments/assets/f0d6186f-9a6c-40bd-b03b-6cfe320e36b7)
while using "1d"as filter

**Comment by remg427** [comment]
Hello,
thank you for using MISP42.
MISP42 is in short a wrapper of MISP API endpoints.
Could you test the same queries using MISP REST client on the GUI? Please report if you see different results via MISP REST client and mispgetioc?

**Comment by node011** [comment]
When testing with the MISP API directly, even with the date specified, I am getting the same response as the output from mispgetioc.
<img width="934" alt="bug1" src="https://github.com/user-attachments/assets/bde1b4a8-34ad-4a11-ae4c-46998a24bc21">
<img width="254" alt="bug-2" src="https://github.com/user-attachments/assets/5a771c6c-c165-404c-a8be-632aceb18831">

**Comment by remg427** [comment]
Hi thank you for feedback. MISP42 commands work as expected (similar to the MISP REST API). you may check out the latest version on splunkbase 4.4.0 for other improvments
