### ISSUE TITLE
Misp and Splunk clustering

### ISSUE THREAD

**Issue by drejoe** [remg427/misp42splunk#39]
Hi,

Trying to run Misp42splunk on a clustered Splunk environment.

When trying to run "mispsearch" or "mispsight" on the Search Head the app "thinks" is should pass the execution on to the indexer cluster. This causes a lot of errors like the line below (one line per indexer in the cluster):
[splunkindexer01] NoSectionError at "/pack/splunk/lib/python2.7/ConfigParser.py", line 330 : No section: 'mispsetup'

I've seen a simuler problem in another 3th party app for Splunk.

Hope this gives a little sense ;-)
Best regards //Torben

**Comment by remg427** [comment]
ou runningHi,
which version of Splunk are you running?
try the package on the github v2.0.12m it should work.
just tested on 6-index cluster

**Comment by drejoe** [comment]
Hello,
Running on Spunk version 7.2.1

**Comment by remg427** [comment]
it was a typo.
App is not tested on clustered environment for splunk version 7.1 or 7.2 up to 7.0 only
I will have a look at boolean local & distributed to see if there are some changes

**Comment by drejoe** [comment]
Thanks - with version 2.0.12 I don't get any errors.
