### ISSUE TITLE
Feature request: integreate MISP iocs into Splunk Enterprise Security intel files

### ISSUE THREAD

**Issue by marcnil815** [remg427/misp42splunk#40]
Hi

This is great work. Much appreciated.

One of the features of Splunk Enterprise Security (ES) is to pull threat feeds as CSV and let ES perform the matching (Threat Activity feature of ES). Splunk ES cannot POST a JSON request to the new MISP rest API, so the CSVs have to be created beforehand and then downloaded via the built in mechanism.

This means the analyst using ES is administrator dependent and changes to the csv (for instance adding extra fields to return), mut be changed in the script that created the CSV files regularly.

So here is a feature request for this app: let the app download the IOCs, put it in the right place, add it as a local threat feed, and let ES do its work with the information.

- the user **must** be able to select from the MISP app what do download, i.e. "domain" or "file_hash". Must be matcheable ES fields. Default is to_ids=true and published=true. Time range optional.
- the user **must** be able to paste the JSON POST for more granular selection.
- all multivalue fields **_must_** be split, i.e. domain|ip must be split into doman and ip respectively.
- the resulting CSV files to be merged **_should_** only contain one type (for backwards compatibility). Older ES versions cannot handle "event_id,file_name,file_hash" but only "event_id,file_name". Also makes for cleaner separation.
- the user **should** be able to select which fields to return (event_id,value, etc) and change the feed fields in ES accordingly.

Input to the different matching fields in ES can be provided.
The MISP app does not need to necessarily add the feeds in ES. As long as the CSV files are present on the system and can be accessed _outside_ of the MISP app, the user can add the feeds locally in ES. The app does not need to take care of that.

Br
Marc

**Comment by remg427** [comment]
Hi Marc,
thanks for your FR.
Regarding ES, I was planning to use mispgetioc in a search 
1 - to pull from MISP (for example domain values)
2 - then format the fields including renaming of the fields to match the expected format of ES (description,domain,weight)
3  - and save the output as local CSV file then saving it under local_domain_intel.csv.
all this ca be done without admin right (power user in ES is enough)
I will review your request for a complete analysis but for the flexibility of JSON file to post (2nd bullet) you may be interested by version 3 where I have started to make a MISP API wrapper mispapireport where you can set most of the fields of the JSON file to call the misp api.
I will quickly improve this version with a parameter jsonpost where you will be able to directly submit a JSON request

**Comment by marcnil815** [comment]
Hi

ouputcsv would have been my workaround as well :) Use getmispioc to create csv files once pr. hour or by ad-hoc if needed demand and use those files to add to ES as threat feeds.

ad 2)
if the feed is added as a local threat feed ("lookup://misp_domains.csv") the renaming must be done anyway in the threat feed settings

ad 3)
oooh....I haven't thought of that. You need the renaming 2) for this of course. I am just wondering if it should append the data to the file, as other mechanisms may populate local_domain_intel.csv; or if ES ignores the file after an initial merge. In other words I wonder what happens if you delete the data in the local_domain_intel.csv. Does ES purge the data from the merged intel? I don't think so....

re: mispapireport. That would be excellent.

The tricky part is still making sure that domain|ip and similar get split into their components. Can't have a multivalue field in a threat feed.

This is really excellent work :)

**Comment by remg427** [comment]
mispgetioc has a new param pipesplit which split domain|ip and similar into 2 fields while the fields type and values keep the original entry
if pipesplit=y attribute domain|ip with value www.example.com|1.1.1.1 will give

| misp_domain | misp_ip | misp_type | misp_value |
|------------------|------------|--------------|----------------|
| www.example.com | 1.1.1.1   | domain\|ip  | www.example.com\|1.1.1.1 | 

if pipesplit=n or not provided the output will be as follows

| misp_domain_p_ip | misp_type | misp_value |
|------------------|--------------|----------------|
| www.example.com\|1.1.1.1   | domain\|ip  | www.example.com\|1.1.1.1 |

**Comment by marcnil815** [comment]
That is excellent. In the meaintime I think I have figured out how to get the data into the ES Threat Activity chain.

1. .  Create a Saved Search (Report) that gets data from MISP and uses outpulookupcsv to save the data. The Saved Search must run in the SA-ThreatIntelligenve contect.
2. Create a new lookup definition based on that file. Same context: SA-ThreatIntelligence
3. Add a new threat feed with a local "lookup://" pulling that file.

As to the splitting: will "type=domain pipesplit=y" also provide me with values from "domain|ip"?

**Comment by jlachesk** [comment]
@marcnil815 -- for what it's worth, that's the exact approach I've used to implement MISP -> Splunk ES as well. 

I broke it down into a few feeds for better traceability -- Domains, IPs, User Agents, URLs, Files, Hashes with a separate report/lookup for each. Then each is implemented as a unique feed into ES with the type "misp_intel" and a name like "misp_intel_domains". This makes things a little more organized in places like the Threat Artifacts dashboard.

**Comment by remg427** [comment]
Thanks
I will copy your procedures as a use case. 
Regarding the types I think you should test with
type="domain,domain|ip" to get also mv attributes

Le 17 janvier 2019 08:19:18 GMT+01:00, marcnil815 <notifications@github.com> a écrit :
>That is excellent. In the meaintime I think I have figured out how to
>get the data into the ES Threat Activity chain.
>
>1. .  Create a Saved Search (Report) that gets data from MISP and uses
>outpulookupcsv to save the data. The Saved Search must run in the
>SA-ThreatIntelligenve contect.
>2. Create a new lookup definition based on that file. Same context:
>SA-ThreatIntelligence
>3. Add a new threat feed with a local "lookup://" pulling that file.
>
>As to the splitting: will "type=domain pipesplit=y" also provide me
>with values from "domain|ip"?
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/40#issuecomment-455067547

-- 
Sent with K-9 Mail.
-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
There are also some saved searches to build KV store lookup that could be easily adapted to build those CSV file.
If you come with good searches/lookups they can be shipped in the apps to make it compatible out of the box with ES
The process could be to clone the into the correct apps context
Another improvement could be to build a dashboard with them so people will see the outputs and adapt to their needs
Remi

Le 17 janvier 2019 17:38:33 GMT+01:00, jlachesk <notifications@github.com> a écrit :
>@marcnil815 -- for what it's worth, that's the exact approach I've used
>to implement MISP -> Splunk ES as well. 
>
>I broke it down into a few feeds for better traceability -- Domains,
>IPs, User Agents, URLs, Files, Hashes with a separate report/lookup for
>each. Then each is implemented as a unique feed into ES with the type
>"misp_intel" and a name like "misp_intel_domains". This makes things a
>little more organized in places like the Threat Artifacts dashboard.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/40#issuecomment-455240372

-- 
Sent with K-9 Mail.
-- 
Sent with K-9 Mail.

**Comment by blackundertone** [comment]
Has anyone addressed the retention / expiry of IOC between MISP -> Splunk ES Threat Intel ?
Im also using mispgetioc to collect iocs from MISP to a local lookup, which is monitored and stored in the Threat Intel lists (ip_intel / http_intel etc) - however the problem is that each time the threat intel framework pulls the IOC from the lookup containing the IOC from MISP, the timestamp in the Splunk ES Threat Intel KV store is updated on the indicator to that time. Deduplication works fine, so im not seeing duplicate indicators, but each time the intel is pulled, its a "new" indicator and will never expire. Hopefully ive explained that properly.

**Comment by marcnil815** [comment]
@blackundertone If you set the max age of the threat feed in Splunk the same IOC should no longer be updated after expiry.
Are you saying the "max age" setting doesn't work?

**Comment by marcnil815** [comment]
I guess we can close this feature request. The provided saved searches can be tailored to create the intel files needed.

**Comment by remg427** [comment]
Hi yes
But when I have access to ES platform I will take your instructions to make a step by step on top of saved search
I have found that creating the CSV table in context of misp42splunk and the lookup in thevone of SA-ThreatIntelligence works well
Thanks for your inputs

Le 21 février 2019 23:57:14 GMT+01:00, marcnil815 <notifications@github.com> a écrit :
>I guess we can close this feature request. The provided saved searches
>can be tailored to create the intel files needed.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/40#issuecomment-466202350

-- 
Sent with K-9 Mail.
