### ISSUE TITLE
Invalid key in stanza

### ISSUE THREAD

**Issue by drejoe** [remg427/misp42splunk#43]
Hi Rémi,

Found this 3 lines of Splunk complain (snip below).
Seems that Splunk 7.2.x doesn't allow the "distributed" key any longer.
Is't something you've issued before?

Thanks //Torben

Invalid key in stanza [mispgetioc] in /pack/splunk/etc/apps/misp42splunk/default/commands.conf, line 4: distributed  (value:  false).
	Invalid key in stanza [mispsearch] in /pack/splunk/etc/apps/misp42splunk/default/commands.conf, line 10: distributed  (value:  false).
	Invalid key in stanza [mispsight] in /pack/splunk/etc/apps/misp42splunk/default/commands.conf, line 16: distributed  (value:  false).

**Comment by remg427** [comment]
removed in 2.0.14
