### ISSUE TITLE
Issue in version 2.0.14

### ISSUE THREAD

**Issue by drejoe** [remg427/misp42splunk#45]
Hi Rémi,

Just upgraded to version 2.0.14. But gets the following error now when calling "| mispgetioc last=50d getuuid=y getorg=y geteventtag=y":

TypeError at "/pack/splunk/etc/apps/misp42splunk/bin/mispgetioc.py", line 183 : prepare_config() takes exactly 1 argument (2 given)

Any idea?

Best regards //Torben

**Comment by remg427** [comment]
Sorry fix in version 2.0.15 now pushed on master
