### ISSUE TITLE
misp_tag is not added

### ISSUE THREAD

**Issue by ShimiCohen** [remg427/misp42splunk#49]
Hey,

We're trying to add misp_tag for attributes and is not added when we create alert.
Is it possible?

Thank you,
Shimi

**Comment by remg427** [comment]
Hi,
For the moment, misp_tag is at event level.
Maybe a new field misp_attribute_tag could do the job.

Le 17 janvier 2019 13:33:20 GMT+01:00, ShimiCohen <notifications@github.com> a écrit :
>Hey,
>
>We're trying to add misp_tag for attributes and is not added.
>Is it possible?
>
>Thank you,
>Shimi
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/49

-- 
Sent with K-9 Mail.
-- 
Sent with K-9 Mail.

**Comment by ShimiCohen** [comment]
Unfortunately, we tried and it did not work.
We'd be happy if you could help us

Thank you,
Shimi

**Comment by remg427** [comment]
Hi
I have created (version 2.0.16) this dummy alert in splunk

     index=_* clientip="1.1.1.6" | streamstats count as rc |where rc <2 |dedup clientip
     | rename clientip AS misp_ip_dst | eval eventkey="18eb805b6498a6aeb8a965394a72eeaf" 
     | eval misp_comment="a very important IOC"
     | eval fo_filename="npp.exe" | eval fo_md5="18eb805b6498a6aeb8a965394a72eeaf" 
     |eval fo_text="trojanised notepadplusplus"
     | eval misp_time=round(_time,0) | eval misp_info="malspam" |eval misp_tag="misp-galaxy:mitre-enterprise-attack-attack-pattern=\"Spearphishing Attachment - T1193\",misp-galaxy:ransomware=\"Bad Rabbit\""
     | table eventkey misp_time misp_info misp_tag misp_ip_dst misp_comment fo_filename fo_md5 fo_text

and also set some tags in alert form: CoA,C2,badIP
and everything is created **at event level**
![selection_022](https://user-images.githubusercontent.com/5524371/51446258-cc406d00-1d0f-11e9-9325-25ee95f9a0eb.png)

Could you try on your side?
You could also modify the log level by editing misp_alert_create_event.py line 329

         logging.root.setLevel(logging.DEBUG)

then you have more info on /opt/splunk/var/log/splunk/splunkd.log
Hope it helps

attribute tags are on my TODO list

**Comment by ShimiCohen** [comment]
hey, 
its working only if the alert Not intended to existing event via new parameter "EventID".
We would be happy if you could help.

Shimi

**Comment by remg427** [comment]
Ok my mistake
I'll fix asap

Le 21 janvier 2019 11:00:24 GMT+02:00, ShimiCohen <notifications@github.com> a écrit :
>hey, 
>its working only if the alert Not intended to existing event via new
>parameter "EventID".
>We would be happy if you could help.
>
>Shimi
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/49#issuecomment-455996002

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
added new field misp_attribute_tag
If a CSV string is provided, tags are added to the misp_* attributes and/or objects (on the same line)

**Comment by ShimiCohen** [comment]
Thank you, you helped me a lot!

Shimi
