### ISSUE TITLE
Inconsistency between last= and date_from= for unpublished Events

### ISSUE THREAD

**Issue by jlachesk** [remg427/misp42splunk#50]
The behavior when using last= vs. date_from= is inconsistent with respect to whether the event must be published.

Using the last= operator will only return events **published** in the last [value]; however, using date_from will return all events **created** since [value], regardless of whether they're published.

An ideal solution would to have an additional switch to specify whether unpublished events should be returned or not.

**Comment by remg427** [comment]
boolean field published helps keeping consistency.
