### ISSUE TITLE
mispgetioc no longer pulling misp_description

### ISSUE THREAD

**Issue by blackundertone** [remg427/misp42splunk#56]
Thanks for the ongoing development and improvement, however I just upgraded to the latest release (2.1.0) and I am no longer receiving the misp_description when pulling IOC using mispgetioc into Splunk.

Previously this field contained the uid and details from the IOC and its parent event. This allows back tracking from the indicator to the Event in MISP.

Example:
MISP e19 attribute 5c5256ba-7bfc-4434-aa5f-0fde07a586c2 of type "url" in category "Network activity" (to_ids:True)

**Comment by blackundertone** [comment]
ok, so digging into the mispgetioc.py - I can see why.

The version I was using (2.06) used to have a line to create misp_description

`                        v['misp_description'] = 'MISP e' + str(a['event_id']) + ' attribute ' + str(a['uuid']) + ' of type "' \
                            + str(a['type']) + '" in category "' + str(a['category']) + '" (to_ids:' + str(a['to_ids']) + ')'`

This code has been removed in the later version.

I can partially re-generate the misp_description in Splunk using an eval statement after pulling the ioc data however it also looks like you are not returning the uuid to Splunk

**Comment by blackundertone** [comment]
A quick & dirty fix was to add this line back into mispgetioc.py (at line 284 under misp_to_ids). I now have the misp_description field populating again.

Not sure if this was removed intentionally or planned.

**Comment by remg427** [comment]
Hi,
when migrating to MISP API I removed that line indeed. I am going to restore it.
Btw in current version, you should get **attribute** UUID by setting getuuid=True

**Comment by blackundertone** [comment]
Awesome - thank you - I now see the getuuid flag, and that does present the misp_attribute_uuid to Splunk which also solves my problem nicely.
Once again thanks for your development efforts and for continuous improvements for integration between Splunk < -- > MISP

**Comment by remg427** [comment]
Thanks! 
Getuuid is required for example if you plan to increment sighting counters by uuid when you want to be accurate and not increment all attributes having the same value.
There are some use cases for this.

Le 6 février 2019 23:54:33 GMT+01:00, blackundertone <notifications@github.com> a écrit :
>Awesome - thank you - I now see the getuuid flag, and that does present
>the misp_attribute_uuid to Splunk which also solves my problem nicely.
>Once again thanks for your development efforts and for continuous
>improvements for integration between Splunk < -- > MISP
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/56#issuecomment-461220971

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Hi,
misp_description does not scale well with object. At the moment it returns only one entry.
if you don't mind I would like to make the changes as follow
- by default, misp_description is not returned in result set
- a new flag add_description allows to get the misp_description as a multi value field (for objects) but without the attribute uuid (nicer to use the getuuid flag)
