### ISSUE TITLE
to_ids flag is ignored

### ISSUE THREAD

**Issue by marcnil815** [remg427/misp42splunk#59]
Search:
| mispgetioc to_ids=false last=365d

Expected result:
Should be empty
| mispgetioc to_ids=false last=365d | search misp_to_ids=true

Actual result:
Search not empty
| mispgetioc to_ids=false last=365d | search misp_to_ids=true

**Comment by marcnil815** [comment]
Oh....it's more complicated than that.
Looks like only to_ids=false is ignored.

The following returns 0 results:
| mispgetioc to_ids=true last=365d | search misp_to_ids=false

**Comment by marcnil815** [comment]
Might of course also be a MISP error not a misp42splunk error (running version 2.4.98)

**Comment by remg427** [comment]
Hi,
first version of the MISP API was not handling condition "to_ids=false" properly so I coded only condition "to_ids=true" .
But then it was fixed and I did not adapter in the app.
Thanks for reporting, I hope it is correct now.
I have also improved for objects to reflect all combinations of the flag to_ids and not the last attribute parsed.
