### ISSUE TITLE
TheHive Alerts

### ISSUE THREAD

**Issue by xg5-simon** [remg427/misp42splunk#63]
Hi remg427,

Over on TheHive project you mentioned that there is an alert action in misp42splunk to create a Hive alert. 

In the setup do I need to point to the full url? For example http://myhiveinstance:9000/api/alert

[https://github.com/TheHive-Project/TheHive/issues/252#issuecomment-366163622](url)

**Comment by remg427** [comment]
Hi,
The alert action for TH s now a TA-thehive and no longer part of misp42splunk
And yes you have to provide the full path as mentioned in your example.
Thanks to provide positive or not feedback

Le 18 février 2019 12:23:14 GMT+01:00, Simon <notifications@github.com> a écrit :
>Hi remg427,
>
>Over on TheHive project you mentioned that there is an alert action in
>misp42splunk to create a Hive alert. 
>
>In the setup do I need to point to the full url? For example
>http://myhiveinstance:9000/api/alert
>
>[https://github.com/TheHive-Project/TheHive/issues/252#issuecomment-366163622](url)
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/63

-- 
Sent with K-9 Mail.

**Comment by RANGERBEE** [comment]
Hey Guys,

I left an open issue on TA-TheHive as I need to do a sendalert command from a spl query which worked on old version on misp42 app. Could you help me fix the sendalert issue ?  Error code 1 is all I get.




This new version of misp42 is great, btw, much faster and actually pulls data or throws proper error codes.  Thank you!!!

**Comment by remg427** [comment]
related to TA-thehive
