### ISSUE TITLE
FR: Client certificates are not supported

### ISSUE THREAD

**Issue by remg427** [remg427/misp42splunk#68]
This is a feature request to support client certificates.

Client Side Certificates will be a single file containing the private key and the certificate

**Comment by remg427** [comment]
v2.2.0 implements client cert support. Please download and test on splunk if it works

**Comment by nicksoy** [comment]
Hi Remi,

I tested update 2.2.0 on Splunk Enteprise search head in Windows 10 Pro 64. Specified the PEM certificate file (full path) as required.

It works like a charm. Thanks. This will help a lot of our members integrate the two platforms.

**Comment by remg427** [comment]
published on splunkbase. Thanks for feedback
