### ISSUE TITLE
Get the app vetted for Splunk Cloud

### ISSUE THREAD

**Issue by tr4cefl0w** [remg427/misp42splunk#72]
Currently, the app cannot be used by Splunk Cloud clients because it is not vetted for Splunk Cloud.

The process to have the app vetted is here:
http://dev.splunk.com/view/app-cert/SP-CAAAE85

**Comment by remg427** [comment]
Thanks for notification. Next week is busy but I'll work on it (https + secure storage api keys) asap. It will be version 3.x

Le 28 mars 2019 06:43:22 GMT+01:00, tr4cefl0w <notifications@github.com> a écrit :
>Currently, the app cannot be used by Splunk Cloud clients because it is
>not vetted for Splunk Cloud.
>
>The process to have the app vetted is here:
>http://dev.splunk.com/view/app-cert/SP-CAAAE85
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/72

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Hi process is more complex than expected.
App has been reworked completely to store passwords and other credentials in a secure way and to comply with other cloud-deployement requirements. App now passes the appinspect automatic checks again.
but to have it vetted for cloud deployment the request has to come from a customer of the SaaS solution and I am not nor know anybody that could introduce that request.
So if you want to have it vetted yet, could you ask Splunk for this vetting process
Thanks

**Comment by tr4cefl0w** [comment]
Hi,

Thanks for the great work! I will send the request for vetting the app in the coming days and will keep you posted.

**Comment by tr4cefl0w** [comment]
The vetting request for the app was sent.

**Comment by tr4cefl0w** [comment]
Received the following reply from Splunk support:

> [Cloud Vetting][Liverpool] #4335 3.0.4 - misp42splunk
> Review fails vetting and cannot be installed.
> This is a preliminary report. More issues may be found upon further review. 
> Thank you for your app install request. Your app did not meet security and functionality requirements for Splunk Cloud for the following reasons:
> Blocking Concerns
> •	Secret disclosure in below lines. The 'Config' is saved in log which contains the clear 'misp_key' and 'proxy_password'. This is not permitted in Splunk Cloud. Please remove or mask these clear secrets before logging them.
> o	File: bin/misp42splunk/modalert_misp_alert_sighting_helper.py Line: 277
> o	File: bin/misp42splunk/modalert_misp_alert_create_event_helper.py Line: 457
> •	In below lines, the request url can be an insecure http url which is not permitted in Splunk Cloud. Please make a validator to restrict it to a secure https url.
> o	File: bin/misp42splunk/modalert_misp_alert_create_event_helper.py Line: 358, 373
> o	File: bin/misp42splunk/modalert_misp_alert_sighting_helper.py Line: 215
> o	File: bin/mispapireport.py Line: 370
> o	File: bin/mispgetioc.py Line: 278
> o	File: bin/mispsearch.py Line: 133
> o	File: bin/mispsight.py Line: 118, 132
> Once these issues are remedied you can resubmit your app for review.
> In addition the following changes are recommended: 
> null
> Alternatives: 
> null
>

**Comment by remg427** [comment]
Thanks,
I'll gonna fix these issues

Le 6 juin 2019 18:26:53 GMT+02:00, tr4cefl0w <notifications@github.com> a écrit :
>Received the following reply from Splunk support:>
>>
>> [Cloud Vetting][Liverpool] #4335 3.0.4 - misp42splunk>
>> Review fails vetting and cannot be installed.>
>> This is a preliminary report. More issues may be found upon further
>review. >
>> Thank you for your app install request. Your app did not meet
>security and functionality requirements for Splunk Cloud for the
>following reasons:>
>> Blocking Concerns>
>> •	Secret disclosure in below lines. The 'Config' is saved in log
>which contains the clear 'misp_key' and 'proxy_password'. This is not
>permitted in Splunk Cloud. Please remove or mask these clear secrets
>before logging them.>
>> o	File: bin/misp42splunk/modalert_misp_alert_sighting_helper.py Line:
>277>
>> o	File: bin/misp42splunk/modalert_misp_alert_create_event_helper.py
>Line: 457>
>> •	In below lines, the request url can be an insecure http url which
>is not permitted in Splunk Cloud. Please make a validator to restrict
>it to a secure https url.>
>> o	File: bin/misp42splunk/modalert_misp_alert_create_event_helper.py
>Line: 358, 373>
>> o	File: bin/misp42splunk/modalert_misp_alert_sighting_helper.py Line:
>215>
>> o	File: bin/mispapireport.py Line: 370>
>> o	File: bin/mispgetioc.py Line: 278>
>> o	File: bin/mispsearch.py Line: 133>
>> o	File: bin/mispsight.py Line: 118, 132>
>> Once these issues are remedied you can resubmit your app for review.>
>> In addition the following changes are recommended: >
>> null>
>> Alternatives: >
>> null>
>> >
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/remg427/misp42splunk/issues/72#issuecomment-499568987

-- 
Sent with K-9 Mail.
