### ISSUE TITLE
Add support for MISP Event Threat Level

### ISSUE THREAD

**Issue by xg5-simon** [remg427/misp42splunk#73]
Please add MISP events "Threat Level" as a supported field for mispgetioc. This will allow creating an IOCs weight based on threat level as opposed to TLP in the example searches.

Thanks again for this great app remg427.

**Comment by remg427** [comment]
Hello I will do in coming days
As a work around you may use mispapireport meanwhile.

Le 3 avril 2019 01:39:27 GMT+02:00, Simon <notifications@github.com> a écrit :
>Please add MISP events "Threat Level" as a supported field for
>mispgetioc. This will allow creating an IOCs weight based on threat
>level as opposed to TLP in the example searches.
>
>Thanks again for this great app remg427.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/73

-- 
Sent with K-9 Mail.

**Comment by xg5-simon** [comment]
I will test soon when I am back in front of my PC

**Comment by remg427** [comment]
Added in 2.2.2 and 3.0.0
