### ISSUE TITLE
Possibility to use sendalert

### ISSUE THREAD

**Issue by marcnil815** [remg427/misp42splunk#79]
Hi

I am having trouble using the _sendalert_ feature of Splunk to update/create events in MISP ad-hoc.

`<search here> | <optional and required fields for misp42splunk> |  sendalert misp_alert_create_event <fields?>`

One of the challenges is that the app does not populate the error log (index=_internal) and returns either error code 1 or 2.

So: would it be possible for you to provide a guide on how to perform the ad-hoc search?

Br
Marc

**Comment by cbboggs** [comment]
@marcnil815 we just went through this as well.  The example and docs leave a lot to be desired.   I found that if you're having trouble, check the search.log (via Inspect Job) and you might see the actual STDERR output, if it doesn't actually log to splunkd.log...

In any case, I found that to use sendalert, you need to specify three params:  param.analysis, param.threatlevel, and param.distribution.   Those are the three the script reads from your alert config..  they are just integers, you'll have to play around to get the right values.

We figured this out so we could use sendalert to test why the script wasn't working for us - found out that misp_info is actually a required field (it always fails if we leave it null).

Example:  
`| sendalert misp_alert_create_event param.analysis=2 param.threatlevel=2 param.distribution=0`

**Comment by remg427** [comment]
Hi
thanks for feedback. I was used to the alert form.
I will improve the doc with one example.
Btw I am going to release version 3 reworked with the TA-add on builder app with better logging in search.log
Hope it will fit your expectations

Le 19 avril 2019 20:01:48 GMT+02:00, cbboggs <notifications@github.com> a écrit :
>@marcnil815 we just went through this as well.  The example and docs
>leave a lot to be desired.   I found that if you're having trouble,
>check the search.log (via Inspect Job) and you might see the actual
>STDERR output, if it doesn't actually log to splunkd.log...
>
>In any case, I found that to use sendalert, you need to specify three
>params:  param.analysis, param.threatlevel, and param.distribution.  
>Those are the three the script reads from your alert config..  they are
>just integers, you'll have to play around to get the right values.
>
>We figured this out so we could use sendalert to test why the script
>wasn't working for us - found out that misp_info is actually a required
>field (it always fails if we leave it null).
>
>Example:  
>`| sendalert misp_alert_create_event param.analysis=2
>param.threatlevel=2 param.distribution=0`
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/79#issuecomment-484972623

-- 
Sent with K-9 Mail.

**Comment by marcnil815** [comment]
Excellent work! Very much appreciated.
