### ISSUE TITLE
Nice works! A dashboard example

### ISSUE THREAD

**Issue by ran2** [remg427/misp42splunk#83]
I pull the IoCs from my MISP instance and store the extracts in an index. Then I created these Dashboard.

https://youtu.be/vhbkxoG6jig

[Updated Video] https://youtu.be/H2Z3gwJW7Fc

Here is the xml file....https://www.dropbox.com/s/mgyuom4nksogx2q/cisp__charts.xml?dl=0

**Comment by remg427** [comment]
Thank you very much for feedback. Very impressive work on your side. Have you a page or do you mind if I refer to your work on the use case section as example of what can be done?

Remi

Le 27 avril 2019 20:49:46 GMT+02:00, Frankie Lee <notifications@github.com> a écrit :
>I pull the IoCs from my MISP instance and store the extracts in an
>index. Then I created these Dashboard.
>
>https://youtu.be/vhbkxoG6jig
>
>Here is the xml
>file....https://www.dropbox.com/s/mgyuom4nksogx2q/cisp__charts.xml?dl=0
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/83

-- 
Sent with K-9 Mail.

**Comment by ran2** [comment]
Sure, I just want to share out to the public … I am still working on make the dashboard more interactive say parsing the md5, sha1 or sha256 and create drill down to pint to VirusTotal etc.

**Comment by remg427** [comment]
Hi, sorry I was late to work on the dashboard and link is not working now. Could you share it again, please?

**Comment by remg427** [comment]
Hi, finally I published your dashboard in doc section with a link to your video. Thanks again
