### ISSUE TITLE
Issues retrieving IOCs from MISP

### ISSUE THREAD

**Issue by nicksoy** [remg427/misp42splunk#84]
Hi Remi,

A colleague reported running into issues retrieving MISP IOCs after migrating from misp42splunk 2.2.4 to 3. He's using Splunk Enterprise security 5.2.2. He noted the previous configuration data in the app had been wiped after the upgrade, and he had subsequently repopulated them.

When attempting to receive IOCs from MISP, he receives this error:
"Error in 'script': Getinfo probe failed for external search command 'mispgetioc'." when clicking the MISP_file_intel_last1d or any of the MISP_X

Appreciate any insight you might have on the cause of this error.

**Comment by remg427** [comment]
I'll check asap

Le 1 mai 2019 06:43:10 GMT+02:00, nicksoy <notifications@github.com> a écrit :
>Hi Remi,
>
>A colleague reported running into issues retrieving MISP IOCs after
>migrating from misp42splunk 2.2.4 to 3. He's using Splunk Enterprise
>security 5.2.2. He noted the previous configuration data in the app had
>been wiped after the upgrade, and he had subsequently repopulated them.
>
>When attempting to receive IOCs from MISP, he receives this error:
>"Error in 'script': Getinfo probe failed for external search command
>'mispgetioc'." when clicking the MISP_file_intel_last1d or any of the
>MISP_X
>
>Appreciate any insight you might have on the cause of this error.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/84

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Hi,

Could you check that all saved searches using midpgetioc have been properly updated with the mandatory field misp_instance= ?

Le 1 mai 2019 06:43:10 GMT+02:00, nicksoy <notifications@github.com> a écrit :
>Hi Remi,
>
>A colleague reported running into issues retrieving MISP IOCs after
>migrating from misp42splunk 2.2.4 to 3. He's using Splunk Enterprise
>security 5.2.2. He noted the previous configuration data in the app had
>been wiped after the upgrade, and he had subsequently repopulated them.
>
>When attempting to receive IOCs from MISP, he receives this error:
>"Error in 'script': Getinfo probe failed for external search command
>'mispgetioc'." when clicking the MISP_file_intel_last1d or any of the
>MISP_X
>
>Appreciate any insight you might have on the cause of this error.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/84

-- 
Sent with K-9 Mail.

**Comment by RANGERBEE** [comment]
I also ran into issue, fixed with setting default_misp and installing pymodel lib..




⁣

**Comment by remg427** [comment]
Was pymodel required?

Le 1 mai 2019 23:04:43 GMT+02:00, RANGERBEE <notifications@github.com> a écrit :
>I also ran into issue, fixed with setting default_misp and installing
>pymodel lib..>
>>
>>
>>
>>
>⁣>
>>
>On May 1, 2019, 3:57 PM, at 3:57 PM, "Rémi Séguy"
><notifications@github.com> wrote:>
>>Hi,>
>>>
>>Could you check that all saved searches using midpgetioc have been>
>>properly updated with the mandatory field misp_instance= ?>
>>>
>>Le 1 mai 2019 06:43:10 GMT+02:00, nicksoy <notifications@github.com>
>a>
>>écrit :>
>>>Hi Remi,>
>>>>
>>>A colleague reported running into issues retrieving MISP IOCs after>
>>>migrating from misp42splunk 2.2.4 to 3. He's using Splunk Enterprise>
>>>security 5.2.2. He noted the previous configuration data in the app>
>>had>
>>>been wiped after the upgrade, and he had subsequently repopulated>
>>them.>
>>>>
>>>When attempting to receive IOCs from MISP, he receives this error:>
>>>"Error in 'script': Getinfo probe failed for external search command>
>>>'mispgetioc'." when clicking the MISP_file_intel_last1d or any of
>the>
>>>MISP_X>
>>>>
>>>Appreciate any insight you might have on the cause of this error.>
>>>>
>>>>
>>>-- >
>>>You are receiving this because you are subscribed to this thread.>
>>>Reply to this email directly or view it on GitHub:>
>>>https://github.com/remg427/misp42splunk/issues/84>
>>>
>>-- >
>>Sent with K-9 Mail.>
>>>
>>-- >
>>You are receiving this because you are subscribed to this thread.>
>>Reply to this email directly or view it on GitHub:>
>>https://github.com/remg427/misp42splunk/issues/84#issuecomment-488422988>
>>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/remg427/misp42splunk/issues/84#issuecomment-488426387

-- 
Sent with K-9 Mail.

**Comment by nicksoy** [comment]
Hi guys, 

Thanks for your responses. 

So my colleague's tried the following search query:

| mispgetioc misp_instance=default_misp last=7d type="sha256,domain,ip-dst,text" to_ids=Y getuuid=Y getorg=Y last=1d to_ids=t geteventtag=t
| where isnotnull(misp_email_src) or isnotnull(misp_email_subject) 
| eval weight=case(match(misp_tag,"tlp:white"),20,match(misp_tag,"tlp:green"),40,match(misp_tag,"tlp:amber"),80,match(misp_tag,"tlp:red"),100,true(),50)
| eval description = "MISP e" + misp_event_id | rename misp_email_src AS src_user misp_email_subject AS subject 
| where isnotnull(src_user) or isnotnull(subject) | fields description,src_user,subject,weight 
| outputlookup misp_email_intel.csv

He continues to receive the same error. 

Hasn't tried installing the pymodel library as rangerbee suggested. Is it available through the Splunk search head?

**Comment by remg427** [comment]
Hi,
There are duplicata params in your example. Last= and to_ids=.

In the app you can manage log level. If you raise to DEBUG your colleague should get the maximum info in search.log via inspect job
I'll try the same example on my side
IMHO pymodel is not required
Rémi

Le 2 mai 2019 03:52:27 GMT+02:00, nicksoy <notifications@github.com> a écrit :
>Hi guys, 
>
>Thanks for your responses. 
>
>So my colleague's tried the following search query:
>
>| mispgetioc misp_instance=default_misp last=7d
>type="sha256,domain,ip-dst,text" to_ids=Y getuuid=Y getorg=Y last=1d
>to_ids=t geteventtag=t
>| where isnotnull(misp_email_src) or isnotnull(misp_email_subject) 
>| eval
>weight=case(match(misp_tag,"tlp:white"),20,match(misp_tag,"tlp:green"),40,match(misp_tag,"tlp:amber"),80,match(misp_tag,"tlp:red"),100,true(),50)
>| eval description = "MISP e" + misp_event_id | rename misp_email_src
>AS src_user misp_email_subject AS subject 
>| where isnotnull(src_user) or isnotnull(subject) | fields
>description,src_user,subject,weight 
>| outputlookup misp_email_intel.csv
>
>He continues to receive the same error. 
>
>Hasn't tried installing the pymodel library as rangerbee suggested. Is
>it available through the Splunk search head?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/84#issuecomment-488532275

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Hi, duplicates is not a problem only last entry is taken into account
I typed that query and got result
Could your colleague try a simple
| mispgetioc misp_instance=yourname last=1d ? in debug mode

Also double check local/inputs.conf for the stanza yourname and passwords.conf also


Le 2 mai 2019 03:52:27 GMT+02:00, nicksoy <notifications@github.com> a écrit :
>Hi guys, 
>
>Thanks for your responses. 
>
>So my colleague's tried the following search query:
>
>| mispgetioc misp_instance=default_misp last=7d
>type="sha256,domain,ip-dst,text" to_ids=Y getuuid=Y getorg=Y last=1d
>to_ids=t geteventtag=t
>| where isnotnull(misp_email_src) or isnotnull(misp_email_subject) 
>| eval
>weight=case(match(misp_tag,"tlp:white"),20,match(misp_tag,"tlp:green"),40,match(misp_tag,"tlp:amber"),80,match(misp_tag,"tlp:red"),100,true(),50)
>| eval description = "MISP e" + misp_event_id | rename misp_email_src
>AS src_user misp_email_subject AS subject 
>| where isnotnull(src_user) or isnotnull(subject) | fields
>description,src_user,subject,weight 
>| outputlookup misp_email_intel.csv
>
>He continues to receive the same error. 
>
>Hasn't tried installing the pymodel library as rangerbee suggested. Is
>it available through the Splunk search head?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/84#issuecomment-488532275

-- 
Sent with K-9 Mail.

**Comment by nicksoy** [comment]
Hi Remi,

Thanks for your response. We'll try that and let you know the outcome

**Comment by remg427** [comment]
Hi,
Is there any progress? How can I help?

Le 2 mai 2019 07:47:58 GMT+02:00, nicksoy <notifications@github.com> a écrit :
>Hi Remi,
>
>Thanks for your response. We'll try that and let you know the outcome
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/84#issuecomment-488559538

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Error message was related to missing modules for custom commands (only alerts were working)

**Comment by RANGERBEE** [comment]
hmmm. I will have to check, I may have thought it was working with only alerts....  Thanks!

**Comment by remg427** [comment]
fixed

**Comment by simsimp-cyber** [comment]
hello i am receiving this error message for the same splunk query : External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 62 : ('[MC-PC-E02] no misp instance configured. Please configure an entry for %s', 'default_misp') ".

Can you help please?

**Comment by remg427** [comment]
Hi you need to go to configuration page and create one instance pointing to your MISP instance
Cheers

Le 26 janvier 2023 10:16:32 GMT+01:00, simsimp-cyber ***@***.***> a écrit :
>hello i am receiving this error message for the same splunk query : External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 62 : ('[MC-PC-E02] no misp instance configured. Please configure an entry for %s', 'default_misp') ".
>
>Can you help please?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/84#issuecomment-1404730046
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Sent with K-9 Mail.
