### ISSUE TITLE
Add misp_hostname to MISP_web lookup table

### ISSUE THREAD

**Issue by RichieB2B** [remg427/misp42splunk#92]
I can retrieve the hostname attributes from MISP using `mispgetioc type="hostname"` but I cannot store them in the MISP_web lookup table. Please add a column misp_hostname to the MISP_web lookup table.

**Comment by remg427** [comment]
done.
Thanks for feedback

**Comment by RichieB2B** [comment]
Thanks! I'm fairly new to Splunk, but I also expected misp_hostname to be added to the MISP_web section of [transforms.conf](https://github.com/remg427/misp42splunk/blob/master/misp42splunk/default/transforms.conf). Or is that not required?

**Comment by remg427** [comment]
Hello,
at this stage only kvstores are implemented
If you plan to index misp events then you may develop transforms and props to make it CIM compliant.

Le 9 juin 2019 18:03:35 GMT+02:00, Richie B2B <notifications@github.com> a écrit :
>Thanks! I'm fairly new to Splunk, but I also expected misp_hostname to
>be added to the MISP_web section of
>[transforms.conf](https://github.com/remg427/misp42splunk/blob/master/misp42splunk/default/transforms.conf).
>Or is that not required?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/92#issuecomment-500224566

-- 
Sent with K-9 Mail.
