### ISSUE TITLE
Bug: Proxy variable confusion

### ISSUE THREAD

**Issue by marcnil815** [remg427/misp42splunk#95]
Hi

We upgraded the misp42splunk app on from 2.x to 3.x on three different installalation. All went well except we suddenly got a "no JSON object to decode", i.e. no data to parse.

When we tested on a fresh Splunk all went well, but not in prod.

After a very lengthy troubleshooting effort somebody finally figured out that miså42splunk was reading the proxy settings from other apps, which resulted in the behaviour.

I don't have the source code, but somebody changed "proxy" to "misp_proxy" in "misp_common.py" and everything works now.

Br
Marc

**Comment by remg427** [comment]
Hi,
Thanks for feedback. Feel grateful for effort.
Sorry for lengthy troubleshouting.
Have you checked the box misp_use_proxy in the input defining your MISP instance?
If yes were proxy settings defined in global config of the TA?
Does your setting work for alerts or code has to be adapted there too?.
I am going to reverse engineer once again the TA add on builder and use your tips to fix that.
Thanks again
Remi

Le 18 juin 2019 15:12:07 GMT+02:00, marcnil815 <notifications@github.com> a écrit :
>Hi>
>>
>We upgraded the misp42splunk app on from 2.x to 3.x on three different
>installalation. All went well except we suddenly got a "no JSON object
>to decode", i.e. no data to parse.>
>>
>When we tested on a fresh Splunk all went well, but not in prod.>
>>
>After a very lengthy troubleshooting effort somebody finally figured
>out that miså42splunk was reading the proxy settings from other apps,
>which resulted in the behaviour.>
>>
>I don't have the source code, but somebody changed "proxy" to
>"misp_proxy" in "misp_common.py" and everything works now.>
>>
>Br>
>Marc>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/remg427/misp42splunk/issues/95

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
3.0.6 dict proxy has been renamed misp_proxy

**Comment by fkjensen** [comment]
The lines I changed to make a workaround in 3.0.5 was

if proxy' in credential.content.get('username') and 'proxy_password' in credential.content.get('clear_password'):

to

if 'misp_proxy' in credential.content.get('username') and 'proxy_password' in credential.content.get('clear_password'):

It was conflicting with the app Splunk_TA_nessus which contained a stored password for a username '[credential:Splunk_TA_nessus:__Splunk_TA_nessus_proxy__:]'. 

It seems that Splunk rest calls to '/.../storage/passwords' return all usernames even in different realms. 

The sourcecode in misp_common.py check in 3.0.5 check for all usernames in all realms with a username with 'proxy' inside. 

Hope my explanation helps in defending misp42splunk against configuration of other Splunk apps.

**Comment by remg427** [comment]
Hi, thanks for clarification. I have changed the line accordingly checking for 'misp' and 'proxy' in 3.0.6
On my side I have found that the clear username is 'misp42splunk_proxy'
I hope it covers all cases
