### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Shersto** [remg427/misp42splunk#96]
I have done everything in the documentation and I continually get this error inside Splunk as if the data input is not found within the local configuration.

 External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 41 : ('local/inputs.conf does not exist. Please configure an inputs entry for %s', u'misp') ". 

Any ideas?

**Comment by remg427** [comment]
Hello,
what version do you run and on Windows or Linux?
do you have a file under  _SPLUNK_PATH + os.sep + 'etc' + os.sep + 'apps' + os.sep + app_name + os.sep + 'local' + os.sep + 'inputs.conf' ? on standard install on Linux it is /opt/splunk/etc/apps/misp42splunk/local/inputs.conf

**Comment by Shersto** [comment]
Ubuntu 14 is the OS and the standard path /opt/splunk/etc/apps/misp42splunk/local/. I just noticied there is no Inputs.conf in this directory /opt/splunk/etc/apps/misp42splunk/local/

[cid:image001.png@01D53722.360F0F30]<https://www.mcafee.com/us/index.html>
Ryan Sherstobitoff
Senior Analyst – Major Campaigns
Advanced Threat Research
D: 408.497.8339



The information contained in this email message may be privileged, confidential and protected from disclosure. If you are not the intended recipient, any review, dissemination, distribution or copying is strictly prohibited. If you have received this email message in error, please notify the sender by reply email and delete the message and any attachments.

**Comment by Shersto** [comment]
So I attempted to add Inputs.conf to the directory /opt/splunk/etc/apps/misp42splunk/local/. Still fails with the same error.

External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 41 : ('local/inputs.conf does not exist. Please configure an inputs entry for %s', u'default_misp') "

**Comment by Shersto** [comment]
Hard coded the path now to the inputs.conf and get this error

External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/misp_common.py", line 38 : ('local/inputs.conf does not contain any stanza %s ', 'misp://default_misp') ".

**Comment by remg427** [comment]
please restore the code as it was
once the app is installed, launch it there several tabs
the first one is inputs 
click on button create new input and provide requested information
this will create inputs.conf in /local/ with a stanza related to the stanza name
if you select "default" as misp instance name, there will [misp://default]
it should work

**Comment by Shersto** [comment]
interesting as the app hangs loading the inputs part, so this should appear in the inputs [misp://default]?

**Comment by Shersto** [comment]
I just manually added the information into inputs, now I get this error 
Could not locate the time (_time) field on some results returned from the external search command 'mispgetioc'.

**Comment by remg427** [comment]
mispgetioc is a reporting command there is no _time field; typically you save or use it as a lookup

**Comment by remg427** [comment]
> 
> 
> interesting as the app hangs loading the inputs part, so this should appear in the inputs [misp://default]?

have you restarted splunk after installation to be sure REST API endpoint is there?

**Comment by RANGERBEE** [comment]
I ran into similar issue. Fix for me is if anything funny happens,  delete /local dir and restart splunkweb.. All is fresh again..

**Comment by Shersto** [comment]
It just 'began' working now, but had to manually edit the inputs.conf

**Comment by remg427** [comment]
Ok thank you for feed back will try to reproduce it. What version of splunk? Was it fresh install or upgrade? And for MISP42splunk was it new or upgrade? If upgrade from version before 3.x?

Le 11 juillet 2019 14:22:55 GMT+02:00, Shersto <notifications@github.com> a écrit :
>It just 'began' working now, but had to manually edit the inputs.conf
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/96#issuecomment-510463096

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
But i use only ubuntu 18 or 16 at the oldest. 

Le 11 juillet 2019 14:22:55 GMT+02:00, Shersto <notifications@github.com> a écrit :
>It just 'began' working now, but had to manually edit the inputs.conf
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/96#issuecomment-510463096

-- 
Sent with K-9 Mail.

**Comment by buggypanda** [comment]
External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "/opt/splunk/etc/apps/misp42splunk/bin/mispgetioc.py", line 219 : Missing "json_request", "eventid", "last" or "date" argument ". 

I'm receiving this error. There is no data retrieved to Splunk

**Comment by remg427** [comment]
Hello
Indeed you need to use one of those parameters

Le 11 novembre 2019 11:29:53 GMT+01:00, buggypanda <notifications@github.com> a écrit :
>External search command 'mispgetioc' returned error code 1. Script
>output = "error_message=Exception at
>"/opt/splunk/etc/apps/misp42splunk/bin/mispgetioc.py", line 219 :
>Missing "json_request", "eventid", "last" or "date" argument ". 
>
>I'm receiving this error. There is no data retrieved to Splunk
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/96#issuecomment-552385552

-- 
Sent with K-9 Mail.

**Comment by negar-ad** [comment]
Hi everybody
I have done everything and I continually get this error when I search this (| mispgetevent misp_instance=MISP date=10d)  inside Splunk. how can i fix it?

External search command 'mispgetevent' returned error code 1. Script output = "error_message=ConnectionError at "C:\Program Files\Splunk\Python-3.7\lib\site-packages\requests\adapters.py", line 516 : HTTPSConnectionPool(host='172.16.3.195', port=443): Max retries exceeded with url: /events/restSearch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BC2EC337C8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')) "

**Comment by remg427** [comment]
Hi,
Thank you for using MISP42.
Have you defined an instance with name MISP?
Have you tested without checking server certificate?
I didn't tested on Windows so maybe a library is missing or behaves differently

Br

-- 
Sent with K-9 Mail.

**Comment by IsaacA11** [comment]
Hello, I installed the app on an ES SH, however, when I go to Configuration The page opens but I get a loading icon and does not either load any inputs neither gives me the option to create a new one, Please let me know if you have any idea of what could be happening.
