### ISSUE TITLE
Indexing data

### ISSUE THREAD

**Issue by pcyr4417** [remg427/misp42splunk#97]
What is the process of indexing this data, are you indexing on the search head? I see no data after input is created. Thanks.

**Comment by remg427** [comment]
Hello,

Inputs is just used at the moment to create MISP instances for alert actions and custom search. There is no code to pull data every x second but you may had it.
Just using a feature of addon builder for a cleaner process to create MISP instances and store api key in password storage

For indexing MISP attributes or create lookups I use mispgetioc ( examples in saved searches to leverage threat Intel)
Hope it is clearer

Le 12 juillet 2019 17:07:33 GMT+02:00, pcyr4417 <notifications@github.com> a écrit :
>What is the process of indexing this data, are you indexing on the
>search head? I see no data after input is created. Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/misp42splunk/issues/97

-- 
Sent with K-9 Mail.

**Comment by pcyr4417** [comment]
Makes sense, just noticed the setting for time frequency in the configuration so it was a little confusing. Thanks you.
