### ISSUE TITLE
Feature Request for additional paramaters and chunk search in mispsearch

### ISSUE THREAD

**Issue by J0oo** [remg427/misp42splunk#98]
Hi,

first of all, thank you for your work on the addon.

I use your addon for different use cases. Mainly it is used by
a correlation search to refine my result with the MISP-Event-ID.
The mispsearch is triggered for each Splunk event and searches
for a specific event by attribute. 
However, I have problems with the large amount of data that needs to be searched. 
The mispsearch aborts and I lose the Splunk event data I'm searching for.
The Splunk search doesn't abort so I cannot see if it is totally complete or not.

My request is to add additional (optional) parameters for mispsearch to decrease the amount of data to search:
- event_timestamp
- last

Another question is whether you can implement chunked searches. As far as I know
you can use limit and page to search on specific chunks on the MISP instance. 
For example run the search on chunks with limit 100 over all pages till a event
is found.

Maybe it is possible to implement. Thank you. :)

Best Regards

**Comment by remg427** [comment]
Hi, I have implemented last= and limit= 
You can always use existing option json_request to set your custom JSON body request

**Comment by J0oo** [comment]
It is working fine. Thanks a lot.
